"""
Hardware CI/CD Pipeline Generator — Creates GitHub Actions workflows
for automated firmware builds, testing, and deployment.
"""


class CIPipelineGenerator:
    """Generates CI/CD pipeline configurations for firmware projects."""

    def generate_github_actions(
        self,
        board: str = "esp32dev",
        platform: str = "espressif32",
        run_tests: bool = True,
        ota_deploy: bool = False,
        device_ip: str = "",
    ) -> str:
        """Generate a GitHub Actions workflow YAML for PlatformIO firmware."""
        test_step = ""
        if run_tests:
            test_step = """
      - name: Run unit tests
        run: pio test -e {board} --without-uploading

      - name: Static analysis (MISRA check)
        run: pio check -e {board} --severity=high --skip-packages
""".format(board=board)

        ota_step = ""
        if ota_deploy and device_ip:
            ota_step = f"""
      - name: Deploy OTA
        if: github.ref == 'refs/heads/main'
        run: |
          pip install esptool
          python -m espota -i {device_ip} -p 3232 -f .pio/build/{board}/firmware.bin
"""

        return f"""# Parakram CI/CD — Auto-generated firmware pipeline
name: Firmware CI/CD

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  PLATFORMIO_BOARD: {board}
  PLATFORMIO_PLATFORM: {platform}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board: [{board}]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PlatformIO
        run: |
          pip install platformio
          pio pkg update

      - name: Compile firmware
        run: pio run -e ${{{{ matrix.board }}}}
{test_step}
      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{{{ matrix.board }}}}
          path: |
            .pio/build/${{{{ matrix.board }}}}/firmware.bin
            .pio/build/${{{{ matrix.board }}}}/firmware.elf
          retention-days: 30
{ota_step}
  size-report:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PlatformIO
        run: pip install platformio

      - name: Check firmware size
        run: |
          pio run -e {board} -t size
          echo "## Firmware Size Report" >> $GITHUB_STEP_SUMMARY
          pio run -e {board} -t size 2>&1 | tail -20 >> $GITHUB_STEP_SUMMARY
"""

    def generate_pre_commit_config(self) -> str:
        """Generate pre-commit hooks for firmware repositories."""
        return """# Pre-commit hooks for firmware projects
repos:
  - repo: local
    hooks:
      - id: pio-check
        name: PlatformIO static check
        entry: pio check --skip-packages --severity=medium
        language: system
        files: \\.(c|cpp|h|hpp|ino)$
        pass_filenames: false

      - id: pio-build
        name: PlatformIO build check
        entry: pio run
        language: system
        files: \\.(c|cpp|h|hpp|ino)$
        pass_filenames: false

      - id: clang-format
        name: C/C++ formatting
        entry: clang-format -i --style=Google
        language: system
        files: \\.(c|cpp|h|hpp|ino)$
"""

    def generate_platformio_test(self, board: str = "esp32dev") -> str:
        """Generate a basic PlatformIO unit test template."""
        return f"""// test/test_main.cpp — Generated by Parakram CI
#include <Arduino.h>
#include <unity.h>

void test_setup_completes(void) {{
    TEST_ASSERT_TRUE(true);
}}

void test_wifi_ssid_not_empty(void) {{
    const char* ssid = "TestNetwork";
    TEST_ASSERT_NOT_NULL(ssid);
    TEST_ASSERT_GREATER_THAN(0, strlen(ssid));
}}

void test_sensor_reading_in_range(void) {{
    // Replace with actual sensor read
    float temperature = 25.0;
    TEST_ASSERT_FLOAT_WITHIN(50.0, 25.0, temperature);
}}

void test_pin_configuration(void) {{
    pinMode(LED_BUILTIN, OUTPUT);
    digitalWrite(LED_BUILTIN, HIGH);
    TEST_ASSERT_EQUAL(HIGH, digitalRead(LED_BUILTIN));
}}

void setup() {{
    delay(2000);
    UNITY_BEGIN();
    RUN_TEST(test_setup_completes);
    RUN_TEST(test_wifi_ssid_not_empty);
    RUN_TEST(test_sensor_reading_in_range);
    RUN_TEST(test_pin_configuration);
    UNITY_END();
}}

void loop() {{}}
"""
