"""
Auto-Documentation Generator — Creates README/docs per project.

Generates:
  - Pin diagram (ASCII art)
  - BOM (Bill of Materials)
  - Setup instructions
  - API reference
  - Calibration notes
"""

import json
import os
from datetime import datetime


class DocGenerator:
    """Generates project documentation from golden block configs."""

    def __init__(self):
        self.sections = []

    def generate(self, project_name: str, blocks: list[dict], board: str = "esp32dev") -> str:
        """Generate complete README.md for a firmware project."""
        doc = []

        # Title
        doc.append(f"# {project_name}")
        doc.append(f"")
        doc.append(f"*Auto-generated by Parakram AI Firmware Studio — {datetime.now().strftime('%Y-%m-%d %H:%M')}*")
        doc.append(f"")

        # Overview
        doc.append("## Overview")
        doc.append(f"")
        doc.append(f"| Property | Value |")
        doc.append(f"|---|---|")
        doc.append(f"| Board | `{board}` |")
        doc.append(f"| Components | {len(blocks)} |")
        doc.append(f"| Framework | Arduino (PlatformIO) |")
        doc.append(f"| MISRA C:2012 | ✅ Compliant |")
        doc.append(f"")

        # BOM
        doc.append("## Bill of Materials")
        doc.append("")
        doc.append("| # | Component | Bus | Libraries |")
        doc.append("|---|---|---|---|")
        for i, b in enumerate(blocks, 1):
            libs = ", ".join(b.get("libs", []))
            bus = b.get("bus", "GPIO")
            doc.append(f"| {i} | {b.get('name', b['id'])} | {bus} | {libs} |")
        doc.append("")

        # Pin Diagram
        doc.append("## Pin Assignments")
        doc.append("")
        doc.append("```")
        doc.append("         ┌──────────────────┐")
        doc.append("         │    ESP32 DevKit   │")
        doc.append("         │                   │")

        pin_map = {}
        for b in blocks:
            pins = b.get("pins", {})
            for role, pin in pins.items():
                if isinstance(pin, (int, str)):
                    pin_map[str(pin)] = f"{b['id']}.{role}"

        left_pins = ["3V3", "GND", "15", "2", "4", "16", "17", "5", "18", "19"]
        right_pins = ["VIN", "GND", "13", "12", "14", "27", "26", "25", "33", "32"]

        for lp, rp in zip(left_pins, right_pins):
            l_label = pin_map.get(lp, lp)
            r_label = pin_map.get(rp, rp)
            doc.append(f"    {l_label:>20s} │{lp:>4s}  {rp:<4s}│ {r_label}")

        doc.append("         │                   │")
        doc.append("         │    21(SDA) 22(SCL) │")
        doc.append("         └──────────────────┘")
        doc.append("```")
        doc.append("")

        # Setup Instructions
        doc.append("## Setup")
        doc.append("")
        doc.append("### Prerequisites")
        doc.append("- [PlatformIO](https://platformio.org/install/cli)")
        doc.append("- USB cable for your ESP32 board")
        doc.append("")
        doc.append("### Build & Flash")
        doc.append("```bash")
        doc.append("# Install dependencies")
        doc.append("pio pkg install")
        doc.append("")
        doc.append("# Build")
        doc.append("pio run")
        doc.append("")
        doc.append("# Flash to device")
        doc.append("pio run -t upload")
        doc.append("")
        doc.append("# Monitor serial output")
        doc.append("pio device monitor -b 115200")
        doc.append("```")
        doc.append("")

        # Dependencies
        lib_deps = set()
        for b in blocks:
            for dep in b.get("lib_deps", []):
                lib_deps.add(dep)

        if lib_deps:
            doc.append("## Dependencies")
            doc.append("")
            doc.append("```ini")
            doc.append("# platformio.ini")
            doc.append("lib_deps =")
            for dep in sorted(lib_deps):
                doc.append(f"    {dep}")
            doc.append("```")
            doc.append("")

        # Calibration Notes
        calibratable = [b for b in blocks if b["id"] in {
            "ph_sensor", "tds_meter", "ec_sensor", "turbidity",
            "thermistor", "hx711", "load_cell_hx710",
        }]
        if calibratable:
            doc.append("## Calibration")
            doc.append("")
            doc.append("The following sensors require calibration before first use:")
            doc.append("")
            for b in calibratable:
                doc.append(f"- **{b.get('name', b['id'])}** — Use Parakram's calibration wizard or `calibrator_two_point()` API")
            doc.append("")
            doc.append("See the [Calibration Guide](https://parakram.dev/docs/calibration) for step-by-step instructions.")
            doc.append("")

        # API Reference
        doc.append("## API Reference")
        doc.append("")
        for b in blocks:
            doc.append(f"### {b.get('name', b['id'])}")
            doc.append(f"```c")
            # Extract function declarations from header
            header = b.get("header", "")
            for line in header.split("\\n"):
                line = line.strip()
                if line.startswith("void ") or line.startswith("float ") or \
                   line.startswith("int ") or line.startswith("bool ") or \
                   line.startswith("uint") or line.startswith("String "):
                    doc.append(line)
            doc.append("```")
            doc.append("")

        # Footer
        doc.append("---")
        doc.append(f"*Generated by [Parakram](https://parakram.dev) v1.0 — AI Firmware Studio by Vidyutlabs*")

        return "\n".join(doc)

    def generate_to_file(self, project_dir: str, project_name: str, blocks: list[dict], board: str = "esp32dev"):
        """Write README.md to the project directory."""
        content = self.generate(project_name, blocks, board)
        path = os.path.join(project_dir, "README.md")
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        return path
