"""Batch 7: Final 15 blocks to push past 200 — Smart Home, Camera, Audio, Power."""

BATCH_7_BLOCKS = {
    "sensor": [
        {"id":"ens160","name":"ENS160 Air Quality (AQI)","libs":["Wire.h","ScioSense_ENS160.h"],"lib_deps":["sciosense/ScioSense_ENS160@^1.0.0"],"pins":{"sda":21,"scl":22},"bus":"I2C","addr":"0x53",
         "header":'#ifndef ENS160_H\n#define ENS160_H\nvoid ens160_setup();\nvoid ens160_loop();\nuint8_t ens160_get_aqi();\nuint16_t ens160_get_tvoc();\nuint16_t ens160_get_eco2();\n#endif',
         "source":'#include "ens160.h"\n#include <Wire.h>\n#include <ScioSense_ENS160.h>\nstatic ScioSense_ENS160 ens(ENS160_I2CADDR_1);\nstatic uint8_t _aqi=0;static uint16_t _tvoc=0,_eco2=0;static unsigned long _l=0;\nvoid ens160_setup(){Wire.begin();ens.begin();ens.setMode(ENS160_OPMODE_STD);Serial.println("[ens160] OK");}\nvoid ens160_loop(){if(millis()-_l<1000)return;_l=millis();if(ens.available()){ens.measure(true);_aqi=ens.getAQI();_tvoc=ens.getTVOC();_eco2=ens.geteCO2();}}\nuint8_t ens160_get_aqi(){return _aqi;}\nuint16_t ens160_get_tvoc(){return _tvoc;}\nuint16_t ens160_get_eco2(){return _eco2;}'},
        {"id":"hts221","name":"HTS221 Temp/Humidity","libs":["Wire.h","Adafruit_HTS221.h"],"lib_deps":["adafruit/Adafruit HTS221@^1.0.2"],"pins":{"sda":21,"scl":22},"bus":"I2C","addr":"0x5F",
         "header":'#ifndef HTS221_H\n#define HTS221_H\nvoid hts221_setup();\nvoid hts221_loop();\nfloat hts221_get_temperature();\nfloat hts221_get_humidity();\n#endif',
         "source":'#include "hts221.h"\n#include <Wire.h>\n#include <Adafruit_HTS221.h>\nstatic Adafruit_HTS221 hts;\nstatic float _t=0,_h=0;static unsigned long _l=0;\nvoid hts221_setup(){Wire.begin();if(!hts.begin_I2C()){Serial.println("[hts221] Fail!");return;}hts.setDataRate(HTS221_RATE_1_HZ);Serial.println("[hts221] OK");}\nvoid hts221_loop(){if(millis()-_l<2000)return;_l=millis();sensors_event_t h,t;hts.getEvent(&h,&t);_t=t.temperature;_h=h.relative_humidity;}\nfloat hts221_get_temperature(){return _t;}\nfloat hts221_get_humidity(){return _h;}'},
        {"id":"mcp3008","name":"MCP3008 8-Ch SPI ADC","libs":["SPI.h","Adafruit_MCP3008.h"],"lib_deps":["adafruit/Adafruit MCP3008@^1.1.0"],"pins":{"cs":5},
         "header":'#ifndef MCP3008_H\n#define MCP3008_H\nvoid mcp3008_setup();\nint mcp3008_read(uint8_t channel);\nfloat mcp3008_read_voltage(uint8_t channel);\n#endif',
         "source":'#include "mcp3008.h"\n#include <SPI.h>\n#include <Adafruit_MCP3008.h>\nstatic Adafruit_MCP3008 adc;\nvoid mcp3008_setup(){adc.begin(5);Serial.println("[mcp3008] OK 8ch 10bit");}\nint mcp3008_read(uint8_t c){return adc.readADC(c);}\nfloat mcp3008_read_voltage(uint8_t c){return adc.readADC(c)*3.3/1023.0;}'},
        {"id":"mpu9250","name":"MPU9250 9-DOF IMU","libs":["Wire.h","MPU9250.h"],"lib_deps":["bolderflight/Bolder Flight Systems MPU9250@^1.0.2"],"pins":{"sda":21,"scl":22},"bus":"I2C","addr":"0x68",
         "header":'#ifndef MPU9250_H\n#define MPU9250_H\nvoid mpu9250_setup();\nvoid mpu9250_loop();\nfloat mpu9250_accel_x();\nfloat mpu9250_accel_y();\nfloat mpu9250_accel_z();\nfloat mpu9250_gyro_x();\nfloat mpu9250_gyro_y();\nfloat mpu9250_gyro_z();\nfloat mpu9250_mag_x();\nfloat mpu9250_mag_y();\nfloat mpu9250_mag_z();\n#endif',
         "source":'#include "mpu9250.h"\n#include <Wire.h>\n#include <MPU9250.h>\nstatic MPU9250 imu(Wire,0x68);\nstatic float _ax=0,_ay=0,_az=0,_gx=0,_gy=0,_gz=0,_mx=0,_my=0,_mz=0;static unsigned long _l=0;\nvoid mpu9250_setup(){Wire.begin();if(imu.begin()<0){Serial.println("[mpu9250] Fail!");return;}Serial.println("[mpu9250] OK 9DOF");}\nvoid mpu9250_loop(){if(millis()-_l<50)return;_l=millis();imu.readSensor();_ax=imu.getAccelX_mss();_ay=imu.getAccelY_mss();_az=imu.getAccelZ_mss();_gx=imu.getGyroX_rads();_gy=imu.getGyroY_rads();_gz=imu.getGyroZ_rads();_mx=imu.getMagX_uT();_my=imu.getMagY_uT();_mz=imu.getMagZ_uT();}\nfloat mpu9250_accel_x(){return _ax;}\nfloat mpu9250_accel_y(){return _ay;}\nfloat mpu9250_accel_z(){return _az;}\nfloat mpu9250_gyro_x(){return _gx;}\nfloat mpu9250_gyro_y(){return _gy;}\nfloat mpu9250_gyro_z(){return _gz;}\nfloat mpu9250_mag_x(){return _mx;}\nfloat mpu9250_mag_y(){return _my;}\nfloat mpu9250_mag_z(){return _mz;}'},
    ],
    "actuator": [
        {"id":"heater_pwm","name":"Heater Element (PWM)","libs":[],"lib_deps":[],"pins":{"pwm":25,"temp_adc":34},
         "header":'#ifndef HEATER_H\n#define HEATER_H\nvoid heater_setup();\nvoid heater_set_power(uint8_t pct);\nuint8_t heater_get_power();\nvoid heater_off();\n#endif',
         "source":'#include "heater_pwm.h"\n#include <Arduino.h>\n#define HEATER_PIN 25\nstatic uint8_t _power=0;\nvoid heater_setup(){ledcAttach(HEATER_PIN,1000,8);Serial.println("[heater] OK");}\nvoid heater_set_power(uint8_t p){_power=constrain(p,0,100);ledcWrite(HEATER_PIN,map(_power,0,100,0,255));}\nuint8_t heater_get_power(){return _power;}\nvoid heater_off(){heater_set_power(0);}'},
        {"id":"motor_brushless","name":"Brushless Gimbal Motor","libs":["SimpleFOC.h"],"lib_deps":["askuric/Simple FOC@^2.3.3"],"pins":{"pwm_a":25,"pwm_b":26,"pwm_c":27,"enc":34},
         "header":'#ifndef BLDC_GIMBAL_H\n#define BLDC_GIMBAL_H\nvoid gimbal_setup();\nvoid gimbal_loop();\nvoid gimbal_set_angle(float angle);\nfloat gimbal_get_angle();\n#endif',
         "source":'#include "motor_brushless.h"\n#include <SimpleFOC.h>\nstatic BLDCMotor motor(7);\nstatic BLDCDriver3PWM driver(25,26,27);\nvoid gimbal_setup(){driver.voltage_power_supply=12;driver.init();motor.linkDriver(&driver);motor.controller=MotionControlType::angle;motor.init();Serial.println("[gimbal] OK");}\nvoid gimbal_loop(){motor.loopFOC();motor.move();}\nvoid gimbal_set_angle(float a){motor.target=a;}\nfloat gimbal_get_angle(){return motor.shaft_angle;}'},
    ],
    "communication": [
        {"id":"http_rest_api","name":"REST API Client","libs":["WiFi.h","HTTPClient.h","ArduinoJson.h"],"lib_deps":["bblanchon/ArduinoJson@^7.0.0"],
         "header":'#ifndef REST_API_H\n#define REST_API_H\n#include <Arduino.h>\nvoid rest_setup();\nString rest_get(const char*url);\nString rest_post(const char*url,const char*json);\nint rest_last_code();\n#endif',
         "source":'#include "http_rest_api.h"\n#include <WiFi.h>\n#include <HTTPClient.h>\nstatic int _code=0;\nvoid rest_setup(){Serial.println("[rest] OK");}\nString rest_get(const char*url){HTTPClient http;http.begin(url);_code=http.GET();String r=http.getString();http.end();return r;}\nString rest_post(const char*url,const char*json){HTTPClient http;http.begin(url);http.addHeader("Content-Type","application/json");_code=http.POST(json);String r=http.getString();http.end();return r;}\nint rest_last_code(){return _code;}'},
        {"id":"wifi_mesh","name":"ESP-MESH Network","libs":["painlessMesh.h"],"lib_deps":["painlessMesh/painlessMesh@^1.5.0"],
         "header":'#ifndef WIFI_MESH_H\n#define WIFI_MESH_H\nvoid mesh_setup(const char*prefix,const char*password);\nvoid mesh_loop();\nvoid mesh_broadcast(const char*msg);\nuint32_t mesh_get_node_id();\nint mesh_node_count();\ntypedef void(*mesh_cb)(uint32_t from,const char*msg);\nvoid mesh_on_receive(mesh_cb cb);\n#endif',
         "source":'#include "wifi_mesh.h"\n#include <painlessMesh.h>\nstatic painlessMesh mesh;\nstatic mesh_cb _cb=nullptr;\nvoid _meshRecv(uint32_t from,String&msg){if(_cb)_cb(from,msg.c_str());}\nvoid mesh_setup(const char*p,const char*pw){mesh.init(p,pw,5555);mesh.onReceive(_meshRecv);Serial.printf("[mesh] OK node=%u\\n",mesh.getNodeId());}\nvoid mesh_loop(){mesh.update();}\nvoid mesh_broadcast(const char*m){mesh.sendBroadcast(m);}\nuint32_t mesh_get_node_id(){return mesh.getNodeId();}\nint mesh_node_count(){return mesh.getNodeList().size();}\nvoid mesh_on_receive(mesh_cb cb){_cb=cb;}'},
    ],
    "display": [
        {"id":"seven_seg_max7219","name":"7-Segment MAX7219 8-digit","libs":["LedControl.h"],"lib_deps":["wayoda/LedControl@^1.0.6"],"pins":{"data":23,"cs":5,"clk":18},
         "header":'#ifndef SEG_MAX7219_H\n#define SEG_MAX7219_H\nvoid seg7_setup();\nvoid seg7_show_number(long num);\nvoid seg7_show_float(float num,uint8_t decimals);\nvoid seg7_clear();\nvoid seg7_set_brightness(uint8_t b);\n#endif',
         "source":'#include "seven_seg_max7219.h"\n#include <LedControl.h>\nstatic LedControl lc(23,18,5,1);\nvoid seg7_setup(){lc.shutdown(0,false);lc.setIntensity(0,4);lc.clearDisplay(0);Serial.println("[seg7] OK 8 digits");}\nvoid seg7_show_number(long n){lc.clearDisplay(0);bool neg=n<0;if(neg)n=-n;for(int i=0;i<8&&(n>0||i==0);i++){lc.setDigit(0,i,n%10,false);n/=10;}}\nvoid seg7_show_float(float n,uint8_t d){long mul=1;for(uint8_t i=0;i<d;i++)mul*=10;long val=(long)(n*mul);lc.clearDisplay(0);bool neg=val<0;if(neg)val=-val;for(int i=0;i<8&&(val>0||i==0);i++){lc.setDigit(0,i,val%10,i==d);val/=10;}}\nvoid seg7_clear(){lc.clearDisplay(0);}\nvoid seg7_set_brightness(uint8_t b){lc.setIntensity(0,constrain(b,0,15));}'},
    ],
    "power": [
        {"id":"light_sleep","name":"ESP32 Light Sleep","libs":[],"lib_deps":[],"pins":{},
         "header":'#ifndef LIGHT_SLEEP_H\n#define LIGHT_SLEEP_H\n#include <Arduino.h>\nvoid light_sleep_setup();\nvoid light_sleep_for(uint32_t ms);\nvoid light_sleep_until_pin(uint8_t pin,bool level);\nuint32_t light_sleep_wakeup_cause();\n#endif',
         "source":'#include "light_sleep.h"\n#include <esp_sleep.h>\nvoid light_sleep_setup(){Serial.println("[lsleep] OK");}\nvoid light_sleep_for(uint32_t ms){esp_sleep_enable_timer_wakeup(ms*1000ULL);esp_light_sleep_start();Serial.printf("[lsleep] Woke after %ldms\\n",(long)ms);}\nvoid light_sleep_until_pin(uint8_t pin,bool level){gpio_wakeup_enable((gpio_num_t)pin,level?GPIO_INTR_HIGH_LEVEL:GPIO_INTR_LOW_LEVEL);esp_sleep_enable_gpio_wakeup();esp_light_sleep_start();}\nuint32_t light_sleep_wakeup_cause(){return esp_sleep_get_wakeup_cause();}'},
    ],
    "control_blocks": [
        {"id":"crc_checksum","name":"CRC8/CRC16/CRC32","libs":[],"lib_deps":[],"pins":{},
         "header":'#ifndef CRC_H\n#define CRC_H\n#include <Arduino.h>\nuint8_t crc8(const uint8_t*data,size_t len);\nuint16_t crc16(const uint8_t*data,size_t len);\nuint32_t crc32(const uint8_t*data,size_t len);\n#endif',
         "source":'#include "crc_checksum.h"\nuint8_t crc8(const uint8_t*d,size_t l){uint8_t c=0;for(size_t i=0;i<l;i++){c^=d[i];for(int j=0;j<8;j++)c=(c&0x80)?(c<<1)^0x31:(c<<1);}return c;}\nuint16_t crc16(const uint8_t*d,size_t l){uint16_t c=0xFFFF;for(size_t i=0;i<l;i++){c^=d[i];for(int j=0;j<8;j++)c=(c&1)?(c>>1)^0xA001:(c>>1);}return c;}\nuint32_t crc32(const uint8_t*d,size_t l){uint32_t c=0xFFFFFFFF;for(size_t i=0;i<l;i++){c^=d[i];for(int j=0;j<8;j++)c=(c&1)?(c>>1)^0xEDB88320:(c>>1);}return c^0xFFFFFFFF;}'},
    ],
}
