"""Batch 8: Calibration + Smart Blocks — firmware-side calibrator and anomaly detector."""

BATCH_8_BLOCKS = {
    "control_blocks": [
        # ── Firmware-Side Calibrator — stores calibration in NVS ──
        {"id":"calibrator","name":"Universal Calibrator (NVS)","libs":["Preferences.h"],"lib_deps":[],"pins":{},
         "header":'#ifndef CALIBRATOR_H\n#define CALIBRATOR_H\n#include <Arduino.h>\nvoid calibrator_setup();\nvoid calibrator_set_polynomial(const char*sensor_id, const float*coeffs, uint8_t degree);\nfloat calibrator_apply(const char*sensor_id, float raw);\nvoid calibrator_tare(const char*sensor_id, float current_raw);\nvoid calibrator_two_point(const char*sensor_id, float raw1, float ref1, float raw2, float ref2);\nvoid calibrator_save(const char*sensor_id);\nvoid calibrator_load(const char*sensor_id);\n#endif',
         "source":'#include "calibrator.h"\n#include <Preferences.h>\n#include <math.h>\n#define MAX_SENSORS 16\n#define MAX_DEGREE 4\ntypedef struct {\n  char id[24];\n  float coeffs[MAX_DEGREE+1];\n  uint8_t degree;\n  float tare_offset;\n  bool valid;\n} cal_entry_t;\nstatic cal_entry_t _cals[MAX_SENSORS];\nstatic uint8_t _cnt = 0;\nstatic Preferences _prefs;\nstatic int _find(const char*id) {\n  for (int i = 0; i < _cnt; i++) if (strcmp(_cals[i].id, id) == 0) return i;\n  return -1;\n}\nstatic int _findOrCreate(const char*id) {\n  int idx = _find(id);\n  if (idx >= 0) return idx;\n  if (_cnt >= MAX_SENSORS) return -1;\n  idx = _cnt++;\n  strncpy(_cals[idx].id, id, 23);\n  _cals[idx].degree = 1;\n  _cals[idx].coeffs[0] = 0; _cals[idx].coeffs[1] = 1;\n  _cals[idx].tare_offset = 0;\n  _cals[idx].valid = true;\n  return idx;\n}\nvoid calibrator_setup() {\n  _prefs.begin("cal", false);\n  Serial.println("[cal] OK");\n}\nvoid calibrator_set_polynomial(const char*id, const float*c, uint8_t d) {\n  int idx = _findOrCreate(id);\n  if (idx < 0) return;\n  _cals[idx].degree = min(d, (uint8_t)MAX_DEGREE);\n  for (int i = 0; i <= d; i++) _cals[idx].coeffs[i] = c[i];\n  _cals[idx].valid = true;\n  Serial.printf("[cal] %s: deg=%d\\n", id, d);\n}\nfloat calibrator_apply(const char*id, float raw) {\n  int idx = _find(id);\n  if (idx < 0) return raw;\n  float result = 0, power = 1;\n  raw -= _cals[idx].tare_offset;\n  for (int i = 0; i <= _cals[idx].degree; i++) {\n    result += _cals[idx].coeffs[i] * power;\n    power *= raw;\n  }\n  return result;\n}\nvoid calibrator_tare(const char*id, float raw) {\n  int idx = _findOrCreate(id);\n  if (idx >= 0) { _cals[idx].tare_offset = raw; Serial.printf("[cal] %s tared at %.2f\\n", id, raw); }\n}\nvoid calibrator_two_point(const char*id, float r1, float v1, float r2, float v2) {\n  int idx = _findOrCreate(id);\n  if (idx < 0) return;\n  float slope = (v2 - v1) / (r2 - r1);\n  float intercept = v1 - slope * r1;\n  _cals[idx].degree = 1;\n  _cals[idx].coeffs[0] = intercept;\n  _cals[idx].coeffs[1] = slope;\n  _cals[idx].valid = true;\n  Serial.printf("[cal] %s: y=%.4fx+%.4f\\n", id, slope, intercept);\n}\nvoid calibrator_save(const char*id) {\n  int idx = _find(id);\n  if (idx < 0) return;\n  _prefs.putBytes(id, &_cals[idx], sizeof(cal_entry_t));\n  Serial.printf("[cal] %s saved to NVS\\n", id);\n}\nvoid calibrator_load(const char*id) {\n  int idx = _findOrCreate(id);\n  if (idx < 0) return;\n  size_t len = _prefs.getBytes(id, &_cals[idx], sizeof(cal_entry_t));\n  if (len > 0) Serial.printf("[cal] %s loaded from NVS\\n", id);\n}'},

        # ── Anomaly Detector — firmware-side ──
        {"id":"anomaly_detector","name":"Anomaly Detector","libs":[],"lib_deps":[],"pins":{},
         "header":'#ifndef ANOMALY_DET_H\n#define ANOMALY_DET_H\n#include <Arduino.h>\ntypedef void(*anomaly_cb)(const char*sensor, float value, const char*reason);\nvoid anomaly_setup();\nuint8_t anomaly_add_monitor(const char*name, float min_val, float max_val, float rate_limit);\nbool anomaly_check(uint8_t idx, float value);\nbool anomaly_any_alert();\nvoid anomaly_on_detect(anomaly_cb cb);\nvoid anomaly_reset();\n#endif',
         "source":'#include "anomaly_detector.h"\n#define MAX_MON 32\ntypedef struct {\n  const char* name;\n  float min_val, max_val, rate_limit;\n  float last_val;\n  unsigned long last_time;\n  bool alert;\n} monitor_t;\nstatic monitor_t _m[MAX_MON];\nstatic uint8_t _cnt = 0;\nstatic anomaly_cb _cb = nullptr;\nvoid anomaly_setup() { _cnt = 0; Serial.println("[anomaly] OK"); }\nuint8_t anomaly_add_monitor(const char*n, float mn, float mx, float rl) {\n  if (_cnt >= MAX_MON) return 255;\n  _m[_cnt] = {n, mn, mx, rl, 0, 0, false};\n  return _cnt++;\n}\nbool anomaly_check(uint8_t i, float v) {\n  if (i >= _cnt) return false;\n  monitor_t* m = &_m[i];\n  bool alert = false;\n  const char* reason = "";\n  if (v < m->min_val) { alert = true; reason = "below_min"; }\n  else if (v > m->max_val) { alert = true; reason = "above_max"; }\n  if (m->last_time > 0) {\n    float dt = (millis() - m->last_time) / 1000.0f;\n    if (dt > 0 && abs(v - m->last_val) / dt > m->rate_limit) {\n      alert = true; reason = "rate_exceeded";\n    }\n  }\n  if (v != v) { alert = true; reason = "nan_detected"; }\n  m->last_val = v; m->last_time = millis(); m->alert = alert;\n  if (alert && _cb) _cb(m->name, v, reason);\n  return alert;\n}\nbool anomaly_any_alert() {\n  for (int i = 0; i < _cnt; i++) if (_m[i].alert) return true;\n  return false;\n}\nvoid anomaly_on_detect(anomaly_cb cb) { _cb = cb; }\nvoid anomaly_reset() { for (int i = 0; i < _cnt; i++) _m[i].alert = false; }'},

        # ── Smart Data Publisher — JSON + MQTT auto-publish ──
        {"id":"smart_publisher","name":"Smart Data Publisher","libs":["ArduinoJson.h"],"lib_deps":["bblanchon/ArduinoJson@^7.0.0"],"pins":{},
         "header":'#ifndef SMART_PUB_H\n#define SMART_PUB_H\n#include <Arduino.h>\nvoid publisher_setup(uint32_t interval_ms);\nvoid publisher_add(const char*key, float*value_ptr);\nvoid publisher_loop();\nString publisher_get_json();\ntypedef void(*publish_cb)(const char*json);\nvoid publisher_on_publish(publish_cb cb);\n#endif',
         "source":'#include "smart_publisher.h"\n#include <ArduinoJson.h>\n#define MAX_FIELDS 32\ntypedef struct { const char* key; float* ptr; } field_t;\nstatic field_t _f[MAX_FIELDS];\nstatic uint8_t _cnt = 0;\nstatic uint32_t _interval = 5000;\nstatic unsigned long _last = 0;\nstatic publish_cb _cb = nullptr;\nvoid publisher_setup(uint32_t ms) { _interval = ms; Serial.println("[pub] OK"); }\nvoid publisher_add(const char*k, float*p) { if (_cnt < MAX_FIELDS) _f[_cnt++] = {k, p}; }\nvoid publisher_loop() {\n  if (millis() - _last < _interval) return;\n  _last = millis();\n  String json = publisher_get_json();\n  Serial.println(json);\n  if (_cb) _cb(json.c_str());\n}\nString publisher_get_json() {\n  JsonDocument doc;\n  doc["ts"] = millis();\n  for (int i = 0; i < _cnt; i++) doc[_f[i].key] = *_f[i].ptr;\n  String s; serializeJson(doc, s); return s;\n}\nvoid publisher_on_publish(publish_cb cb) { _cb = cb; }'},
    ],
}
