//! Pre-built automation templates — one-click use-case recipes.
//!
//! These templates let users deploy complete automations instantly,
//! without even needing to type a prompt. This is Parakram's network-effect engine.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Template {
    pub id: String,
    pub name: String,
    pub description: String,
    pub category: String,
    pub icon: String,
    pub difficulty: String,
    pub required_sensors: Vec<String>,
    pub required_actuators: Vec<String>,
    pub prompt: String,
    pub tags: Vec<String>,
}

/// Returns the full built-in template catalog.
pub fn get_all_templates() -> Vec<Template> {
    vec![
        // ====== SMART HOME ======
        Template {
            id: "tpl_smart_thermostat".into(),
            name: "Smart Thermostat".into(),
            description: "Automatically controls a fan or heater based on room temperature with configurable thresholds.".into(),
            category: "Smart Home".into(),
            icon: "🌡️".into(),
            difficulty: "Beginner".into(),
            required_sensors: vec!["drv_bme280".into()],
            required_actuators: vec!["drv_relay".into()],
            prompt: "When the temperature goes above 28 degrees, turn on the cooler fan relay. When it drops below 25, turn it off. Add 1 degree hysteresis.".into(),
            tags: vec!["hvac".into(), "temperature".into(), "comfort".into()],
        },
        Template {
            id: "tpl_intruder_alarm".into(),
            name: "Intruder Alarm System".into(),
            description: "PIR motion detection triggers a loud buzzer alarm and sends an MQTT alert to your phone.".into(),
            category: "Security".into(),
            icon: "🚨".into(),
            difficulty: "Beginner".into(),
            required_sensors: vec!["drv_pir".into()],
            required_actuators: vec!["drv_buzzer".into()],
            prompt: "When PIR motion is detected, sound the buzzer at 2000 Hz for 3 seconds and publish an MQTT message to 'alerts/motion' with payload 'INTRUDER DETECTED'.".into(),
            tags: vec!["security".into(), "motion".into(), "alarm".into()],
        },
        Template {
            id: "tpl_door_monitor".into(),
            name: "Door Open/Close Monitor".into(),
            description: "Reed switch detects door state changes, logs timestamps, and sends BLE notifications.".into(),
            category: "Security".into(),
            icon: "🚪".into(),
            difficulty: "Beginner".into(),
            required_sensors: vec!["drv_reed".into()],
            required_actuators: vec!["drv_buzzer".into()],
            prompt: "Monitor the reed switch door_state. When the door opens, beep the buzzer once at 1000 Hz for 200ms and send a BLE notification with 'DOOR_OPEN'. When it closes, notify 'DOOR_CLOSED'.".into(),
            tags: vec!["door".into(), "security".into(), "monitoring".into()],
        },
        Template {
            id: "tpl_smart_light".into(),
            name: "Ambient Light Controller".into(),
            description: "Automatically adjusts LED brightness based on ambient light levels for energy savings.".into(),
            category: "Smart Home".into(),
            icon: "💡".into(),
            difficulty: "Intermediate".into(),
            required_sensors: vec!["drv_bh1750".into()],
            required_actuators: vec!["drv_ws2812".into()],
            prompt: "Read ambient light from BH1750. When light drops below 100 lux, turn on WS2812 LEDs to warm white. When it goes above 300 lux, turn them off. Use smooth thresholds.".into(),
            tags: vec!["lighting".into(), "ambient".into(), "energy".into()],
        },

        // ====== AGRICULTURE ======
        Template {
            id: "tpl_auto_irrigation".into(),
            name: "Smart Irrigation System".into(),
            description: "Monitors soil moisture and automatically waters plants when the soil gets too dry.".into(),
            category: "Agriculture".into(),
            icon: "🌱".into(),
            difficulty: "Beginner".into(),
            required_sensors: vec!["drv_soil_cap".into()],
            required_actuators: vec!["drv_solenoid".into()],
            prompt: "Read soil moisture every 30 seconds. When soil_moisture drops below 30%, open the solenoid valve for 10 seconds to water the plant, then close it. Don't water again for at least 5 minutes.".into(),
            tags: vec!["irrigation".into(), "garden".into(), "water".into(), "plants".into()],
        },
        Template {
            id: "tpl_greenhouse".into(),
            name: "Greenhouse Climate Controller".into(),
            description: "Full greenhouse automation: temperature, humidity, and ventilation control with data logging.".into(),
            category: "Agriculture".into(),
            icon: "🏡".into(),
            difficulty: "Advanced".into(),
            required_sensors: vec!["drv_bme280".into(), "drv_soil_cap".into(), "drv_bh1750".into()],
            required_actuators: vec!["drv_fan_pwm".into(), "drv_solenoid".into(), "drv_relay".into()],
            prompt: "Monitor temperature, humidity, soil moisture, and light. If temp exceeds 32°C, run the fan at 80%. If humidity drops below 40%, open solenoid for 5s. If soil moisture below 25%, water for 8 seconds. Log all sensor readings via MQTT every 60 seconds.".into(),
            tags: vec!["greenhouse".into(), "climate".into(), "farming".into()],
        },
        Template {
            id: "tpl_hydroponics".into(),
            name: "Hydroponics pH & TDS Monitor".into(),
            description: "Continuously monitors water pH and dissolved solids for optimal nutrient levels in hydroponic systems.".into(),
            category: "Agriculture".into(),
            icon: "🧪".into(),
            difficulty: "Intermediate".into(),
            required_sensors: vec!["drv_ph".into(), "drv_tds".into()],
            required_actuators: vec!["drv_oled_ssd1306".into(), "drv_buzzer".into()],
            prompt: "Read pH and TDS every 10 seconds. Display current values on OLED. If pH goes below 5.5 or above 7.5, sound buzzer alarm. If TDS goes above 1500ppm, publish MQTT alert to 'hydro/alerts'.".into(),
            tags: vec!["hydroponics".into(), "ph".into(), "nutrients".into()],
        },

        // ====== HEALTH & SAFETY ======
        Template {
            id: "tpl_air_quality".into(),
            name: "Indoor Air Quality Monitor".into(),
            description: "Tracks CO2 and volatile organic compounds, alerts when air quality degrades.".into(),
            category: "Health".into(),
            icon: "🫁".into(),
            difficulty: "Beginner".into(),
            required_sensors: vec!["drv_ccs811".into()],
            required_actuators: vec!["drv_oled_ssd1306".into(), "drv_buzzer".into()],
            prompt: "Read CO2 and TVOC every 5 seconds. Display on OLED. If CO2 exceeds 1000 ppm, sound buzzer at 1500 Hz for 1 second. Publish readings via MQTT to 'air/quality' every 30 seconds.".into(),
            tags: vec!["air".into(), "co2".into(), "health".into(), "ventilation".into()],
        },
        Template {
            id: "tpl_gas_leak".into(),
            name: "Gas Leak Detector".into(),
            description: "Detects dangerous gas levels and triggers an emergency alarm with MQTT notification.".into(),
            category: "Safety".into(),
            icon: "⛽".into(),
            difficulty: "Beginner".into(),
            required_sensors: vec!["drv_mq2".into()],
            required_actuators: vec!["drv_buzzer".into(), "drv_relay".into()],
            prompt: "Read gas sensor every 2 seconds. If gas_ppm exceeds 300, immediately sound buzzer continuously at 3000 Hz and publish MQTT emergency alert to 'safety/gas_leak'. Also cut power via relay as a safety shutoff.".into(),
            tags: vec!["gas".into(), "safety".into(), "emergency".into(), "lpg".into()],
        },
        Template {
            id: "tpl_pulse_monitor".into(),
            name: "Heart Rate & SpO2 Monitor".into(),
            description: "Wearable health monitor that tracks heart rate and blood oxygen saturation in real time.".into(),
            category: "Health".into(),
            icon: "❤️".into(),
            difficulty: "Intermediate".into(),
            required_sensors: vec!["drv_max30102".into()],
            required_actuators: vec!["drv_oled_ssd1306".into()],
            prompt: "Read heart_rate and spo2 every 2 seconds from MAX30102. Display on OLED. If heart rate exceeds 120 BPM or SpO2 drops below 92%, sound an alert buzzer and publish to MQTT 'health/vitals'.".into(),
            tags: vec!["health".into(), "heart".into(), "oximeter".into(), "wearable".into()],
        },

        // ====== INDUSTRIAL & ENERGY ======
        Template {
            id: "tpl_power_monitor".into(),
            name: "Solar Panel Power Monitor".into(),
            description: "Monitors voltage, current, and wattage from solar panels with real-time OLED display.".into(),
            category: "Energy".into(),
            icon: "☀️".into(),
            difficulty: "Intermediate".into(),
            required_sensors: vec!["drv_ina219".into()],
            required_actuators: vec!["drv_oled_ssd1306".into()],
            prompt: "Read voltage, current, and power from INA219 every 5 seconds. Display all three on OLED. Log via MQTT to 'energy/solar' every 30 seconds. If voltage drops below 11V, publish alert 'LOW_BATTERY'.".into(),
            tags: vec!["solar".into(), "energy".into(), "power".into(), "battery".into()],
        },
        Template {
            id: "tpl_industrial_temp".into(),
            name: "Industrial Furnace Monitor".into(),
            description: "High-temperature monitoring using thermocouple with safety shutoff for industrial ovens.".into(),
            category: "Industrial".into(),
            icon: "🔥".into(),
            difficulty: "Advanced".into(),
            required_sensors: vec!["drv_max6675".into()],
            required_actuators: vec!["drv_relay".into(), "drv_buzzer".into(), "drv_oled_ssd1306".into()],
            prompt: "Read thermocouple temperature every 2 seconds. Display on OLED. If temperature exceeds 250°C, cut the heating relay immediately and sound buzzer alarm. Publish all readings to MQTT 'industrial/furnace'.".into(),
            tags: vec!["industrial".into(), "furnace".into(), "thermocouple".into(), "safety".into()],
        },

        // ====== ROBOTICS ======
        Template {
            id: "tpl_obstacle_avoidance".into(),
            name: "Obstacle Avoidance Robot".into(),
            description: "Ultrasonic-guided robot that navigates around obstacles using motor control.".into(),
            category: "Robotics".into(),
            icon: "🤖".into(),
            difficulty: "Intermediate".into(),
            required_sensors: vec!["drv_hcsr04".into()],
            required_actuators: vec!["drv_motor_dc".into()],
            prompt: "Read ultrasonic distance every 100ms. If distance is less than 20cm, stop motors. If distance is between 20-50cm, slow motors to 40% speed. If distance is more than 50cm, run at full speed. Log distance via MQTT every 500ms.".into(),
            tags: vec!["robot".into(), "navigation".into(), "obstacle".into(), "motor".into()],
        },
        Template {
            id: "tpl_gesture_robot".into(),
            name: "Gesture-Controlled Arm".into(),
            description: "Control a servo-based robotic arm using hand gestures detected by APDS9960.".into(),
            category: "Robotics".into(),
            icon: "🦾".into(),
            difficulty: "Advanced".into(),
            required_sensors: vec!["drv_apds9960".into()],
            required_actuators: vec!["drv_servo".into(), "drv_oled_ssd1306".into()],
            prompt: "Read gesture from APDS9960 every 200ms. If UP gesture, move servo to 180 degrees. If DOWN, move to 0 degrees. If LEFT, move to 90 degrees. If RIGHT, move to 45 degrees. Display current gesture and angle on OLED.".into(),
            tags: vec!["gesture".into(), "arm".into(), "servo".into(), "control".into()],
        },
        Template {
            id: "tpl_balance_bot".into(),
            name: "Self-Balancing Bot".into(),
            description: "IMU-stabilized two-wheeled platform using PID control for autonomous balancing.".into(),
            category: "Robotics".into(),
            icon: "⚖️".into(),
            difficulty: "Advanced".into(),
            required_sensors: vec!["drv_mpu6050".into()],
            required_actuators: vec!["drv_motor_dc".into(), "drv_oled_ssd1306".into()],
            prompt: "Read IMU acceleration_y every 10ms. Calculate tilt angle. If tilting forward (accel_y > 0.3), drive motors forward proportionally. If tilting backward (accel_y < -0.3), drive reverse. Display tilt angle on OLED. Clamp motor speed between 0-100%.".into(),
            tags: vec!["balance".into(), "imu".into(), "pid".into(), "bot".into()],
        },

        // ====== WEATHER & ENVIRONMENT ======
        Template {
            id: "tpl_weather_station".into(),
            name: "Personal Weather Station".into(),
            description: "Complete weather monitoring with temperature, humidity, pressure, light, and rain detection.".into(),
            category: "Weather".into(),
            icon: "🌤️".into(),
            difficulty: "Intermediate".into(),
            required_sensors: vec!["drv_bme280".into(), "drv_bh1750".into(), "drv_rain".into()],
            required_actuators: vec!["drv_oled_ssd1306".into()],
            prompt: "Read temperature, humidity, pressure from BME280, light from BH1750, and rain level every 10 seconds. Display all on OLED cycling through screens. Publish all readings to MQTT 'weather/station' every 60 seconds. If rain detected, publish alert.".into(),
            tags: vec!["weather".into(), "station".into(), "outdoor".into(), "climate".into()],
        },

        // ====== AQUATICS ======
        Template {
            id: "tpl_aquarium".into(),
            name: "Smart Aquarium Controller".into(),
            description: "Monitors water temperature, controls heater and lights on schedule, with pH alerts.".into(),
            category: "Aquatics".into(),
            icon: "🐠".into(),
            difficulty: "Intermediate".into(),
            required_sensors: vec!["drv_ds18b20".into(), "drv_ph".into()],
            required_actuators: vec!["drv_relay".into(), "drv_ws2812".into(), "drv_oled_ssd1306".into()],
            prompt: "Read water temperature every 30 seconds. If below 24°C, turn on heater relay. If above 27°C, turn off. Read pH every 60 seconds. If pH below 6 or above 8.5, sound alarm. Display temp and pH on OLED. Set WS2812 to blue.".into(),
            tags: vec!["aquarium".into(), "fish".into(), "water".into()],
        },

        // ====== LOGISTICS ======
        Template {
            id: "tpl_cold_chain".into(),
            name: "Cold Chain Temperature Logger".into(),
            description: "Continuous temperature logging for perishable goods transport with breach alerts.".into(),
            category: "Logistics".into(),
            icon: "❄️".into(),
            difficulty: "Beginner".into(),
            required_sensors: vec!["drv_ds18b20".into()],
            required_actuators: vec!["drv_buzzer".into(), "drv_oled_ssd1306".into()],
            prompt: "Read temperature every 10 seconds. Display on OLED. Log to MQTT 'logistics/coldchain' every 30 seconds. If temperature exceeds 8°C or drops below -2°C, sound continuous buzzer alarm and publish emergency MQTT alert 'COLD_CHAIN_BREACH'.".into(),
            tags: vec!["cold chain".into(), "logistics".into(), "food safety".into()],
        },

        // ====== PETS ======
        Template {
            id: "tpl_pet_feeder".into(),
            name: "Automatic Pet Feeder".into(),
            description: "Timer-based feeding system with servo-controlled dispensing and weight verification.".into(),
            category: "Pets".into(),
            icon: "🐕".into(),
            difficulty: "Intermediate".into(),
            required_sensors: vec!["drv_hx711".into()],
            required_actuators: vec!["drv_servo".into(), "drv_buzzer".into(), "drv_oled_ssd1306".into()],
            prompt: "Every 8 hours (28800000ms), rotate servo to 90 degrees to dispense food, wait 3 seconds, rotate back to 0. Sound a short buzzer beep to call the pet. Read weight from load cell and display on OLED. Publish feeding event to MQTT 'pets/feeder'.".into(),
            tags: vec!["pet".into(), "feeder".into(), "automatic".into(), "dog".into(), "cat".into()],
        },
    ]
}
