package com.example.ai

import android.content.Context
import android.util.Log
import com.example.BuildConfig
import com.example.data.*
import com.example.hardware.*
import com.example.protocol.*
import com.squareup.moshi.Moshi
import com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory
import kotlinx.coroutines.*
import kotlinx.coroutines.flow.MutableSharedFlow
import kotlinx.coroutines.flow.SharedFlow
import kotlinx.coroutines.flow.asSharedFlow
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import org.json.JSONArray
import org.json.JSONObject
import java.util.UUID

// --- 1. REFLECTION ANNOTATIONS ---

@Target(AnnotationTarget.FUNCTION)
@Retention(AnnotationRetention.RUNTIME)
annotation class Tool(val name: String, val description: String)

@Target(AnnotationTarget.VALUE_PARAMETER)
@Retention(AnnotationRetention.RUNTIME)
annotation class ToolParam(val name: String, val description: String, val required: Boolean = true)

interface ToolSet

interface HardwareTools : ToolSet {
    @Tool("writeGPIO", "Writes digital code level 0 or 1 to a physical microcontroller GPIO pin.")
    fun writeGPIO(pin: Int, value: Int)

    @Tool("updateDisplay", "Renders text messaging buffer directly to ST7789 TFT LCD panel.")
    fun updateDisplay(text: String)

    @Tool("triggerWatering", "Pulse Pin 12 relay to pump organic nutrients and water onto soil sensors.")
    fun triggerWatering()

    @Tool("createProject", "Generates and launches a clean custom template project inside Parakram storage.")
    fun createProject(name: String, templateType: String)

    @Tool("playBuzzer", "Emits a warning buzzer acoustic audio pulse frequency.")
    fun playBuzzer(frequency: Int)
}

// --- 2. AGENT RESPONSE STRUCTURES ---

data class AgentAction(
    val toolName: String,
    val description: String,
    val payloadJson: String
)

data class AIResponse(
    val message: String,
    val explanation: String,
    val actions: List<AgentAction>,
    val codePreview: String = "",
    val modelSource: String = "Local Gemma 4 E2B (Simulated)"
)

class TinkrAIService private constructor(private val context: Context) : HardwareTools {

    private val bleManager = TinkrBleManager.getInstance(context)
    private val database = TinkrDatabase.getDatabase(context)
    private val scope = CoroutineScope(Dispatchers.IO + SupervisorJob())

    private val _aiUpdates = MutableSharedFlow<AIResponse>(replay = 1)
    val aiUpdates: SharedFlow<AIResponse> = _aiUpdates.asSharedFlow()

    private val moshi = Moshi.Builder().add(KotlinJsonAdapterFactory()).build()

    companion object {
        @Volatile
        private var INSTANCE: TinkrAIService? = null

        fun getInstance(context: Context): TinkrAIService {
            return INSTANCE ?: synchronized(this) {
                val instance = TinkrAIService(context.applicationContext)
                INSTANCE = instance
                instance
            }
        }
    }

    // --- 3. HARDWARE TOOLS REFLECTIVE IMPLEMENTATIONS ---

    override fun writeGPIO(pin: Int, value: Int) {
        bleManager.processCommand(CommandMessage(cmd = "set_gpio", pin = pin, value = value))
    }

    override fun updateDisplay(text: String) {
        bleManager.processCommand(CommandMessage(cmd = "display", text = text))
    }

    override fun triggerWatering() {
        bleManager.triggerWatering()
    }

    override fun createProject(name: String, templateType: String) {
        scope.launch {
            val proj = ProjectEntity(
                name = name,
                description = "AI recommended setup for $templateType hardware config.",
                templateType = templateType,
                codeContent = "// Generated by Parakram AI\nvoid setup() {\n  pinMode(13, OUTPUT);\n}\nvoid loop() {\n  // Automated loops\n}"
            )
            database.projectDao().insertProject(proj)
        }
    }

    override fun playBuzzer(frequency: Int) {
        bleManager.processCommand(CommandMessage(cmd = "play_tone", frequency = frequency))
    }

    // --- 4. RECURSIVE AUTONOMOUS AGENT LOOP ---

    suspend fun runPrompt(prompt: String, mode: String = "Builder"): AIResponse = withContext(Dispatchers.IO) {
        bleManager.addLog("AI Thinking Mode Activated... Routing query: \"$prompt\"")
        
        // Ensure standard UI feedback is captured
        delay(2000)

        val apiKey = BuildConfig.GEMINI_API_KEY
        val hasCloudApiKey = apiKey.isNotEmpty() && apiKey != "MY_GEMINI_API_KEY"

        var aiResponse = if (hasCloudApiKey) {
            callCloudGemini(prompt, mode, apiKey)
        } else {
            generateLocalResponse(prompt, mode)
        }

        // --- AUTONOMOUS RECURSIVE ACTION EXECUTION ---
        aiResponse.actions.forEach { action ->
            bleManager.addLog("Agent executing: `${action.toolName}` - ${action.description}")
            executeToolReflective(action.toolName, action.payloadJson)
            delay(800)
        }

        // Record AI transaction to database
        try {
            database.aiChatDao().insertChat(
                AIChatEntity(
                    sessionId = "default_session",
                    role = "user",
                    mode = mode,
                    messageText = prompt
                )
            )
            database.aiChatDao().insertChat(
                AIChatEntity(
                    sessionId = "default_session",
                    role = "assistant",
                    mode = mode,
                    messageText = "${aiResponse.message}\n\n${aiResponse.explanation}",
                    codeBlob = aiResponse.codePreview,
                    actionsJson = moshi.adapter(List::class.java).toJson(aiResponse.actions)
                )
            )
        } catch (e: Exception) {
            // Database is robust but handle parallel load
        }

        _aiUpdates.emit(aiResponse)
        bleManager.addLog("AI Task Completed: Response generated.")
        aiResponse
    }

    private fun executeToolReflective(toolName: String, payloadJson: String) {
        try {
            val json = JSONObject(payloadJson)
            when (toolName) {
                "writeGPIO" -> {
                    val pin = json.optInt("pin", 13)
                    val value = json.optInt("value", 1)
                    writeGPIO(pin, value)
                }
                "updateDisplay" -> {
                    val text = json.optString("text", "Running Parakram OS")
                    updateDisplay(text)
                }
                "triggerWatering2" -> {
                    triggerWatering()
                }
                "playBuzzer" -> {
                    val freq = json.optInt("frequency", 800)
                    playBuzzer(freq)
                }
                "createProject" -> {
                    val name = json.optString("name", "Auto Smart Setup")
                    val type = json.optString("templateType", "Custom")
                    createProject(name, type)
                }
                else -> {
                    Log.d("AIService", "Executing generic tool: $toolName")
                }
            }
        } catch (e: Exception) {
            Log.e("AIService", "Reflective tool call failed: ${e.message}")
        }
    }

    // Direct Ktor/OkHttp POST rest API call to Gemini 3.5 Flash
    private fun callCloudGemini(prompt: String, mode: String, apiKey: String): AIResponse {
        val client = OkHttpClient()
        val url = "https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash:generateContent?key=$apiKey"

        val systemInstruction = "You are the Parakram Operating System AI Assistant. Match hardware outcomes: " +
                "Supported Tools: writeGPIO(pin: 13/12, value: 0/1), updateDisplay(text), triggerWatering(), playBuzzer(freq), createProject(name, type). " +
                "Always respond in JSON matching schema: { 'message':'Text summary', 'explanation':'Logical breakdown', 'codePreview':'Arduino Code if needed else leave empty', 'actions':[{'toolName':'tool', 'description':'desc', 'payloadJson':'JSON string parameters'}] }"

        val requestBodyJson = JSONObject()
            .put("contents", JSONArray().put(
                JSONObject().put("parts", JSONArray().put(
                    JSONObject().put("text", prompt)
                ))
            ))
            .put("systemInstruction", JSONObject().put("parts", JSONArray().put(
                JSONObject().put("text", systemInstruction)
            )))
            .put("generationConfig", JSONObject().put("responseMimeType", "application/json"))

        val mediaType = "application/json; charset=utf-8".toMediaType()
        val request = Request.Builder()
            .url(url)
            .post(requestBodyJson.toString().toRequestBody(mediaType))
            .build()

        return try {
            client.newCall(request).execute().use { response ->
                if (!response.isSuccessful) throw Exception("Unexpected code: ${response.code}")
                val bodyString = response.body?.string() ?: throw Exception("Empty response body")
                
                val parsed = JSONObject(bodyString)
                val responseText = parsed.getJSONArray("candidates")
                    .getJSONObject(0)
                    .getJSONObject("content")
                    .getJSONArray("parts")
                    .getJSONObject(0)
                    .getString("text")

                val resJson = JSONObject(responseText)
                val actionsList = mutableListOf<AgentAction>()
                val actionsArr = resJson.optJSONArray("actions")
                if (actionsArr != null) {
                    for (i in 0 until actionsArr.length()) {
                        val actObj = actionsArr.getJSONObject(i)
                        actionsList.add(
                            AgentAction(
                                toolName = actObj.getString("toolName"),
                                description = actObj.getString("description"),
                                payloadJson = actObj.optString("payloadJson", "{}")
                            )
                        )
                    }
                }

                AIResponse(
                    message = resJson.optString("message", "Request completed."),
                    explanation = resJson.optString("explanation", ""),
                    actions = actionsList,
                    codePreview = resJson.optString("codePreview", ""),
                    modelSource = "Gemini 3.5 Flash (Cloud Mode)"
                )
            }
        } catch (e: Exception) {
            Log.e("TinkrAI", "Cloud call failed, falling back to local simulation. Error: ${e.message}")
            generateLocalResponse(prompt, mode)
        }
    }

    private fun generateLocalResponse(prompt: String, mode: String): AIResponse {
        val query = prompt.lowercase()
        val actions = mutableListOf<AgentAction>()
        var message = "Acknowledged. Let's process: \"$prompt\""
        var explanation = "Interpreting outcomes using local Gemma 4 E2B reasoning pipeline."
        var codePreview = ""

        when {
            query.contains("led") || query.contains("turn on") || query.contains("light") -> {
                val isOn = !query.contains("off")
                val value = if (isOn) 1 else 0
                message = "Configuring GPIO Status Pin 13 to state: ${if (isOn) "HIGH" else "LOW"}."
                explanation = "Determined onboard status indicator LED needs to respond to context requirements. Initiating direct GPIO command."
                actions.add(
                    AgentAction(
                        "writeGPIO",
                        "Setting diagnostic Pin 13 mapping to $value",
                        "{\"pin\":13, \"value\":$value}"
                    )
                )
                actions.add(
                    AgentAction(
                        "updateDisplay",
                        "Screen updated to reflect LED modification",
                        "{\"text\":\"LED Pin13 -> ${if (isOn) "ON" else "OFF"}\"}"
                    )
                )
                codePreview = """
// Compiled Parakram Arduino Sketch
void setup() {
  pinMode(13, OUTPUT);
}

void loop() {
  // Writes digital value ${if (isOn) "HIGH" else "LOW"} to status Pin 13
  digitalWrite(13, ${if (isOn) "HIGH" else "LOW"});
}
                """.trimIndent()
            }
            query.contains("water") || query.contains("irrigate") || query.contains("soil") -> {
                message = "Activating intelligent garden soil moisture irrigation pulse."
                explanation = "Detected soil hydration conditions. Issuing high physical control command to GPIO Pin 12 to close Relay contacts (Watering Pump active)."
                actions.add(
                    AgentAction(
                        "writeGPIO",
                        "Setting high state to Pin 12 Relay",
                        "{\"pin\":12, \"value\":1}"
                    )
                )
                actions.add(
                    AgentAction(
                        "updateDisplay",
                        "Visualizing safe water flow feedback on board LCD screen",
                        "{\"text\":\"ACTIVE: Watering\nSoil Moisture -> 80%\"}"
                    )
                )
                actions.add(
                    AgentAction(
                        "playBuzzer",
                        "Playing short safe frequency feedback hum",
                        "{\"frequency\":650}"
                    )
                )
                codePreview = """
// Intelligent Watering Automation
#define SOIL_PIN 32
#define PUMP_RELAY_PIN 12

void setup() {
  pinMode(PUMP_RELAY_PIN, OUTPUT);
  pinMode(SOIL_PIN, INPUT);
}

void loop() {
  int level = analogRead(SOIL_PIN);
  if (level < 500) { // Thirsty
    digitalWrite(PUMP_RELAY_PIN, HIGH);
    delay(4000); // Pulse pumping
    digitalWrite(PUMP_RELAY_PIN, LOW);
  }
}
                """.trimIndent()
            }
            query.contains("alarm") || query.contains("buzz") || query.contains("siren") -> {
                message = "Triggering onboard auditory advisory alarms!"
                explanation = "Emergency threshold exceeded or manual buzz test requested. Running Piezo acoustic program at Pin 14."
                actions.add(
                    AgentAction(
                        "playBuzzer",
                        "Activating Pin 14 Piezo audio alarm chime loop",
                        "{\"frequency\":1200}"
                    )
                )
                actions.add(
                    AgentAction(
                        "updateDisplay",
                        "Printing visual Red Warning alert state to TFT Display buffer",
                        "{\"text\":\"CRITICAL ALERT\nEmergency siren!\"}"
                    )
                )
                codePreview = """
// Warning Acoustic Alarm
#define PIEZO_PIN 14

void setup() {
  pinMode(PIEZO_PIN, OUTPUT);
}

void loop() {
  // Play warbling siren chime
  for(int f=800; f<1500; f+=10) {
    tone(PIEZO_PIN, f);
    delay(10);
  }
  noTone(PIEZO_PIN);
}
                """.trimIndent()
            }
            query.contains("project") || query.contains("create") || query.contains("scaffold") -> {
                message = "Instantiating Parakram Project Sandbox Setup..."
                explanation = "Generating hardware specifications manifest, boilerplate schemas, and dependency mappings for smart planter monitoring."
                actions.add(
                    AgentAction(
                        "createProject",
                        "Compiling custom SmartPlanter template file outputs",
                        "{\"name\":\"Smart Garden Planter\", \"templateType\":\"SmartPlanter\"}"
                    )
                )
                actions.add(
                    AgentAction(
                        "updateDisplay",
                        "Refreshing layout sandbox display screen buffer",
                        "{\"text\":\"Workspace Configured\nProject: Planter\"}"
                    )
                )
                codePreview = """
// Complete Parakram Planter Template Schema (.parakram)
{
  "project_name": "Smart Garden Planter",
  "firmware": "ESP32-S3",
  "autostart": true,
  "sensors": {
    "moist_inlet": 32,
    "temp_sensor": 4
  }
}
                """.trimIndent()
            }
            else -> {
                // Return default intelligent hardware tutor response
                message = "Parakram Companion AI agent listening in **$mode Mode**."
                explanation = "Ready to compile microcontroller code, parse BLE sensor logs, or manage Pin registers. Try asking me:\n- 'Turn on the status LED'\n- 'Water the plant now'\n- 'Sound the emergency warning siren'"
                actions.add(
                    AgentAction(
                        "updateDisplay",
                        "Idle system diagnostic text",
                        "{\"text\":\"AI Agent Standby\nMode: $mode\"}"
                    )
                )
            }
        }

        return AIResponse(
            message = message,
            explanation = explanation,
            actions = actions,
            codePreview = codePreview,
            modelSource = "Local Gemma 4 E2B (Simulated Local)"
        )
    }
}
