//! Renders a valid Python ROS 2 launch file from a composed node graph.

use super::NodeDef;

pub fn render(nodes: &[NodeDef], platform: &str, device_ids: &[String]) -> String {
    let mut lines: Vec<String> = Vec::new();

    lines.push("from launch import LaunchDescription".into());
    lines.push("from launch_ros.actions import Node".into());
    lines.push("from launch.actions import DeclareLaunchArgument".into());
    lines.push("from launch.substitutions import LaunchConfiguration".into());
    lines.push("import os".into());
    lines.push("".into());
    lines.push(format!("# Generated by Parakram ROS Graph Engine — platform: {platform}"));
    lines.push(format!("# Device fleet: {}", if device_ids.is_empty() {
        "auto-discovered".into()
    } else {
        device_ids.join(", ")
    }));
    lines.push("".into());
    lines.push("PARAKRAM_API_URL = os.environ.get('PARAKRAM_API_URL', 'http://localhost:8400')".into());
    lines.push("PARAKRAM_TOKEN   = os.environ.get('PARAKRAM_TOKEN', '')".into());
    lines.push("".into());
    lines.push("def generate_launch_description():".into());
    lines.push("    return LaunchDescription([".into());

    for node in nodes {
        let params_str = format_params(&node.parameters, 8);
        let remaps_str = format_remaps(&node.remappings, 8);

        lines.push(format!("        Node("));
        lines.push(format!("            package='{}',", node.package));
        lines.push(format!("            executable='{}',", node.executable));
        lines.push(format!("            name='{}',", node.name));
        lines.push(format!("            parameters=[{{"));
        lines.push(params_str);
        // Inject Parakram env vars for parakram_ros nodes
        if node.package == "parakram_ros" {
            lines.push("                'parakram_api_url': PARAKRAM_API_URL,".into());
            lines.push("                'parakram_token': PARAKRAM_TOKEN,".into());
        }
        lines.push(format!("            }}],"));
        if !node.remappings.is_empty() {
            lines.push(format!("            remappings=["));
            lines.push(remaps_str);
            lines.push(format!("            ],"));
        }
        lines.push(format!("        ),"));
    }

    lines.push("    ])".into());

    lines.join("\n")
}

fn format_params(params: &serde_json::Value, indent: usize) -> String {
    let pad = " ".repeat(indent);
    match params {
        serde_json::Value::Object(map) => {
            map.iter()
                .map(|(k, v)| format!("{pad}    '{k}': {},", json_to_py(v)))
                .collect::<Vec<_>>()
                .join("\n")
        }
        _ => String::new(),
    }
}

fn format_remaps(remaps: &[[String; 2]], indent: usize) -> String {
    let pad = " ".repeat(indent);
    remaps.iter()
        .map(|[from, to]| format!("{pad}    ('{from}', '{to}'),"))
        .collect::<Vec<_>>()
        .join("\n")
}

fn json_to_py(v: &serde_json::Value) -> String {
    match v {
        serde_json::Value::Bool(b) => if *b { "True".into() } else { "False".into() },
        serde_json::Value::Number(n) => n.to_string(),
        serde_json::Value::String(s) => format!("'{s}'"),
        serde_json::Value::Array(arr) => {
            let items: Vec<String> = arr.iter().map(json_to_py).collect();
            format!("[{}]", items.join(", "))
        }
        serde_json::Value::Null => "None".into(),
        serde_json::Value::Object(_) => "{}".into(),
    }
}
