"""Takes block sequence → full firmware project."""

from dataclasses import dataclass
from pathlib import Path

from config import TARGET_MCUS


@dataclass
class FirmwareProject:
    """A complete, buildable firmware project."""
    target_mcu: str
    main_c: str
    cmake_content: str
    includes: list[str]
    block_count: int
    estimated_flash_kb: int
    estimated_ram_kb: int


def compose_firmware(
    blocks: list[dict],
    target_mcu: str = "esp32s3",
    project_name: str = "parakram_firmware",
) -> FirmwareProject:
    """Compose extracted code blocks into a complete firmware project.

    Steps:
      1. Resolve include dependencies across blocks
      2. Order blocks by dependency graph (topological sort)
      3. Generate main.c with app_main() calling blocks in order
      4. Generate CMakeLists.txt for the target MCU
      5. Estimate resource usage (flash, RAM)
    """
    mcu = TARGET_MCUS.get(target_mcu)
    if not mcu:
        raise ValueError(f"Unknown MCU: {target_mcu}")

    all_includes: set[str] = set()
    all_bodies: list[str] = []
    all_signatures: list[str] = []

    for block in blocks:
        all_includes.update(block.get("includes", []))
        all_bodies.append(block.get("body", ""))
        all_signatures.append(block.get("signature", ""))

    # Generate main.c
    include_lines = "\n".join(f'#include "{inc}"' for inc in sorted(all_includes))
    forward_decls = "\n".join(f"{sig};" for sig in all_signatures)
    function_bodies = "\n\n".join(all_bodies)

    call_lines = "\n    ".join(
        f'{block.get("function_name", "unknown")}();'
        for block in blocks
        if block.get("function_name")
    )

    main_c = f"""// Generated by CodeLM for {target_mcu}
// Blocks: {len(blocks)}

{include_lines}

{forward_decls}

{function_bodies}

void app_main(void) {{
    {call_lines}
}}
"""

    cmake_content = _generate_cmake(project_name, target_mcu, mcu)

    estimated_flash = sum(len(b.get("body", "")) for b in blocks) // 4
    estimated_ram = len(blocks) * 256

    return FirmwareProject(
        target_mcu=target_mcu,
        main_c=main_c,
        cmake_content=cmake_content,
        includes=list(all_includes),
        block_count=len(blocks),
        estimated_flash_kb=estimated_flash // 1024,
        estimated_ram_kb=estimated_ram // 1024,
    )


def _generate_cmake(name: str, target: str, mcu: dict) -> str:
    """Generate CMakeLists.txt for the target platform."""
    if target == "esp32s3":
        return f"""# Generated by CodeLM
cmake_minimum_required(VERSION 3.16)
set(EXTRA_COMPONENT_DIRS "${{CMAKE_SOURCE_DIR}}/components")
include($ENV{{IDF_PATH}}/tools/cmake/project.cmake)
project({name})
"""
    elif target in ("rp2040", "stm32f4"):
        return f"""# Generated by CodeLM
cmake_minimum_required(VERSION 3.13)
project({name} C CXX ASM)
set(CMAKE_C_STANDARD 11)
set(CMAKE_CXX_STANDARD 17)

add_executable(${{PROJECT_NAME}} main.c)
target_compile_options(${{PROJECT_NAME}} PRIVATE -Wall -Wextra -Wpedantic)
"""
    return f"# CodeLM: No CMake template for {target}\n"
