/**
 * @file pal_impl.c  [STM32F4/H7]
 * @brief PAL implementation for STM32F4/H7 using STM32Cube HAL.
 *
 * Peripheral handles (hi2c1, hi2c2, hspi1, hspi2, htim3, htim4, hadc1,
 * huart1, huart2, huart3, hi2s2) are generated by STM32CubeMX and must be
 * defined in the application layer (typically main.c).
 *
 * Compile with: arm-none-eabi-gcc -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 \
 *               -mfloat-abi=hard -mthumb -DUSE_HAL_DRIVER ...
 */

#include "parakram_pal.h"
#include "stm32_hal.h"   /* generic alias for stm32f4xx_hal.h / stm32h7xx_hal.h */

#include <stdarg.h>
#include <stdio.h>
#include <string.h>

/* ── CubeMX-generated peripheral handles ─────────────────────────────────── */

extern I2C_HandleTypeDef   hi2c1, hi2c2;
extern SPI_HandleTypeDef   hspi1, hspi2;
extern TIM_HandleTypeDef   htim3, htim4;
extern ADC_HandleTypeDef   hadc1;
extern UART_HandleTypeDef  huart1, huart2, huart3;
extern I2S_HandleTypeDef   hi2s2;

/* ── Platform identification ─────────────────────────────────────────────── */

const char *pal_get_platform_name(void) { return "STM32F4"; }
pal_mcu_t   pal_get_mcu(void)           { return PAL_MCU_STM32F4; }
uint32_t    pal_get_cpu_freq_hz(void)   { return SystemCoreClock; }

/* ── System ──────────────────────────────────────────────────────────────── */

pal_err_t pal_init(void) {
    /* Enable DWT cycle counter for microsecond-accurate timing. */
    CoreDebug->DEMCR |= CoreDebug_DEMCR_TRCENA_Msk;
    DWT->CYCCNT       = 0U;
    DWT->CTRL        |= DWT_CTRL_CYCCNTENA_Msk;
    return PAL_OK;
}

void pal_reboot(void) {
    NVIC_SystemReset();
}

/*
 * pal_get_free_heap: STM32Cube HAL does not provide heap introspection without
 * FreeRTOS. Return 0; callers should use xPortGetFreeHeapSize() when FreeRTOS
 * is present.
 */
uint32_t pal_get_free_heap(void) {
    return 0U;
}

void pal_feed_watchdog(void) {
    IWDG->KR = 0xAAAAU;
}

/* ── Timing ──────────────────────────────────────────────────────────────── */

void pal_delay_us(uint32_t us) {
    uint32_t start  = DWT->CYCCNT;
    uint32_t ticks  = us * (SystemCoreClock / 1000000U);
    while ((DWT->CYCCNT - start) < ticks) {
        __NOP();
    }
}

void pal_delay_ms(uint32_t ms) {
    HAL_Delay(ms);
}

uint32_t pal_get_time_ms(void) {
    return HAL_GetTick();
}

uint64_t pal_get_time_us(void) {
    return (uint64_t)(DWT->CYCCNT) / (SystemCoreClock / 1000000U);
}

/* ── Logging ─────────────────────────────────────────────────────────────── */

static int s_log_level = PAL_LOG_INFO;

static const char *s_level_str[] = {
    [PAL_LOG_NONE]  = "NONE",
    [PAL_LOG_ERROR] = "ERROR",
    [PAL_LOG_WARN]  = "WARN",
    [PAL_LOG_INFO]  = "INFO",
    [PAL_LOG_DEBUG] = "DEBUG",
};

void pal_log(int level, const char *tag, const char *fmt, ...) {
    if (level > s_log_level || level <= PAL_LOG_NONE) return;
    const char *lvl = (level >= PAL_LOG_ERROR && level <= PAL_LOG_DEBUG)
                      ? s_level_str[level] : "???";
    printf("[%s] %s: ", lvl, tag);
    va_list ap;
    va_start(ap, fmt);
    vprintf(fmt, ap);
    va_end(ap);
    printf("\r\n");
}

/* ── GPIO helpers ────────────────────────────────────────────────────────── */

/*
 * Pin numbering scheme:
 *   0-15  → GPIOA, pins 0-15
 *  16-31  → GPIOB, pins 0-15
 *  32-47  → GPIOC, pins 0-15
 *  48-63  → GPIOD, pins 0-15
 */
static GPIO_TypeDef *pin_to_port(int pin) {
    switch (pin >> 4) {
        case 0:  return GPIOA;
        case 1:  return GPIOB;
        case 2:  return GPIOC;
        case 3:  return GPIOD;
        case 4:  return GPIOE;
#ifdef GPIOF
        case 5:  return GPIOF;
#endif
#ifdef GPIOG
        case 6:  return GPIOG;
#endif
#ifdef GPIOH
        case 7:  return GPIOH;
#endif
        default: return GPIOA;
    }
}

static uint16_t pin_to_mask(int pin) {
    return (uint16_t)(1U << (pin & 0x0F));
}

/* ── GPIO ISR table ──────────────────────────────────────────────────────── */

#define PAL_GPIO_PIN_MAX 64

typedef struct {
    pal_gpio_isr_t cb;
    void          *arg;
} gpio_cb_entry_t;

static gpio_cb_entry_t s_gpio_cbs[PAL_GPIO_PIN_MAX];

/* Called by the HAL from EXTI IRQ handlers. */
void HAL_GPIO_EXTI_Callback(uint16_t gpio_pin) {
    for (int i = 0; i < PAL_GPIO_PIN_MAX; i++) {
        if (pin_to_mask(i) == gpio_pin && s_gpio_cbs[i].cb) {
            s_gpio_cbs[i].cb(s_gpio_cbs[i].arg);
            return;
        }
    }
}

/* ── GPIO API ────────────────────────────────────────────────────────────── */

pal_err_t pal_gpio_set_direction(int pin, pal_gpio_dir_t dir,
                                  bool pullup, bool pulldown) {
    GPIO_InitTypeDef cfg = {0};
    cfg.Pin   = pin_to_mask(pin);
    cfg.Speed = GPIO_SPEED_FREQ_HIGH;

    if (dir == PAL_GPIO_OUTPUT) {
        cfg.Mode = GPIO_MODE_OUTPUT_PP;
    } else {
        cfg.Mode = GPIO_MODE_INPUT;
    }

    if (pullup) {
        cfg.Pull = GPIO_PULLUP;
    } else if (pulldown) {
        cfg.Pull = GPIO_PULLDOWN;
    } else {
        cfg.Pull = GPIO_NOPULL;
    }

    HAL_GPIO_Init(pin_to_port(pin), &cfg);
    return PAL_OK;
}

pal_err_t pal_gpio_set_level(int pin, int level) {
    HAL_GPIO_WritePin(pin_to_port(pin), pin_to_mask(pin),
                      level ? GPIO_PIN_SET : GPIO_PIN_RESET);
    return PAL_OK;
}

int pal_gpio_get_level(int pin) {
    return (HAL_GPIO_ReadPin(pin_to_port(pin), pin_to_mask(pin)) == GPIO_PIN_SET) ? 1 : 0;
}

pal_err_t pal_gpio_set_interrupt(int pin, pal_gpio_intr_t edge,
                                  pal_gpio_isr_t cb, void *arg) {
    if (pin < 0 || pin >= PAL_GPIO_PIN_MAX) return PAL_ERR_INVALID;

    uint32_t mode;
    switch (edge) {
        case PAL_GPIO_INTR_POSEDGE: mode = GPIO_MODE_IT_RISING;         break;
        case PAL_GPIO_INTR_NEGEDGE: mode = GPIO_MODE_IT_FALLING;        break;
        case PAL_GPIO_INTR_ANYEDGE: mode = GPIO_MODE_IT_RISING_FALLING; break;
        default:                    return PAL_ERR_INVALID;
    }

    s_gpio_cbs[pin].cb  = cb;
    s_gpio_cbs[pin].arg = arg;

    GPIO_InitTypeDef cfg = {0};
    cfg.Pin   = pin_to_mask(pin);
    cfg.Mode  = mode;
    cfg.Pull  = GPIO_NOPULL;
    cfg.Speed = GPIO_SPEED_FREQ_HIGH;
    HAL_GPIO_Init(pin_to_port(pin), &cfg);

    /* Enable the matching EXTI IRQ line. The EXTI line index equals the pin
     * bit position within the port (same for all 16 lines). */
    IRQn_Type irq;
    int bit = pin & 0x0F;
    if      (bit == 0)  irq = EXTI0_IRQn;
    else if (bit == 1)  irq = EXTI1_IRQn;
    else if (bit == 2)  irq = EXTI2_IRQn;
    else if (bit == 3)  irq = EXTI3_IRQn;
    else if (bit == 4)  irq = EXTI4_IRQn;
    else if (bit <= 9)  irq = EXTI9_5_IRQn;
    else                irq = EXTI15_10_IRQn;

    HAL_NVIC_SetPriority(irq, 5, 0);
    HAL_NVIC_EnableIRQ(irq);
    return PAL_OK;
}

pal_err_t pal_gpio_remove_interrupt(int pin) {
    if (pin < 0 || pin >= PAL_GPIO_PIN_MAX) return PAL_ERR_INVALID;
    HAL_GPIO_DeInit(pin_to_port(pin), pin_to_mask(pin));
    s_gpio_cbs[pin].cb  = NULL;
    s_gpio_cbs[pin].arg = NULL;
    return PAL_OK;
}

/* ── I2C ─────────────────────────────────────────────────────────────────── */

static I2C_HandleTypeDef *s_i2c_handle[PAL_I2C_MAX_BUSES] = {NULL, NULL};

pal_err_t pal_i2c_init(uint8_t bus, int sda_pin, int scl_pin, uint32_t freq_hz) {
    (void)sda_pin; (void)scl_pin;  /* Pins configured by CubeMX; ignored here. */
    if (bus >= PAL_I2C_MAX_BUSES) return PAL_ERR_INVALID;

    I2C_HandleTypeDef *h = (bus == 0) ? &hi2c1 : &hi2c2;
    s_i2c_handle[bus] = h;

    /* Reconfigure clock speed if it differs from requested. */
    if (h->Init.ClockSpeed != freq_hz) {
        HAL_I2C_DeInit(h);
        h->Init.ClockSpeed      = freq_hz;
        h->Init.DutyCycle       = I2C_DUTYCYCLE_2;
        h->Init.OwnAddress1     = 0;
        h->Init.AddressingMode  = I2C_ADDRESSINGMODE_7BIT;
        h->Init.DualAddressMode = I2C_DUALADDRESS_DISABLE;
        h->Init.OwnAddress2     = 0;
        h->Init.GeneralCallMode = I2C_GENERALCALL_DISABLE;
        h->Init.NoStretchMode   = I2C_NOSTRETCH_DISABLE;
        if (HAL_I2C_Init(h) != HAL_OK) return PAL_ERR_FAIL;
    }
    return PAL_OK;
}

pal_err_t pal_i2c_deinit(uint8_t bus) {
    if (bus >= PAL_I2C_MAX_BUSES || !s_i2c_handle[bus]) return PAL_ERR_INVALID;
    HAL_I2C_DeInit(s_i2c_handle[bus]);
    s_i2c_handle[bus] = NULL;
    return PAL_OK;
}

pal_err_t pal_i2c_read(uint8_t bus, uint8_t addr, uint8_t reg,
                        uint8_t *buf, uint16_t len) {
    if (bus >= PAL_I2C_MAX_BUSES || !s_i2c_handle[bus]) return PAL_ERR_INVALID;
    HAL_StatusTypeDef st = HAL_I2C_Mem_Read(
        s_i2c_handle[bus],
        (uint16_t)(addr << 1),
        (uint16_t)reg,
        I2C_MEMADD_SIZE_8BIT,
        buf, len, 100U);
    return (st == HAL_OK) ? PAL_OK : PAL_ERR_FAIL;
}

pal_err_t pal_i2c_write(uint8_t bus, uint8_t addr, uint8_t reg,
                         const uint8_t *buf, uint16_t len) {
    if (bus >= PAL_I2C_MAX_BUSES || !s_i2c_handle[bus]) return PAL_ERR_INVALID;
    HAL_StatusTypeDef st = HAL_I2C_Mem_Write(
        s_i2c_handle[bus],
        (uint16_t)(addr << 1),
        (uint16_t)reg,
        I2C_MEMADD_SIZE_8BIT,
        (uint8_t *)buf, len, 100U);
    return (st == HAL_OK) ? PAL_OK : PAL_ERR_FAIL;
}

pal_err_t pal_i2c_write_raw(uint8_t bus, uint8_t addr,
                              const uint8_t *buf, uint16_t len) {
    if (bus >= PAL_I2C_MAX_BUSES || !s_i2c_handle[bus]) return PAL_ERR_INVALID;
    HAL_StatusTypeDef st = HAL_I2C_Master_Transmit(
        s_i2c_handle[bus],
        (uint16_t)(addr << 1),
        (uint8_t *)buf, len, 100U);
    return (st == HAL_OK) ? PAL_OK : PAL_ERR_FAIL;
}

pal_err_t pal_i2c_read_raw(uint8_t bus, uint8_t addr,
                             uint8_t *buf, uint16_t len) {
    if (bus >= PAL_I2C_MAX_BUSES || !s_i2c_handle[bus]) return PAL_ERR_INVALID;
    HAL_StatusTypeDef st = HAL_I2C_Master_Receive(
        s_i2c_handle[bus],
        (uint16_t)(addr << 1),
        buf, len, 100U);
    return (st == HAL_OK) ? PAL_OK : PAL_ERR_FAIL;
}

/* ── I2C legacy wrappers (used by all 59 firmware drivers) ──────────────── */
/*
 * All 59 Parakram drivers call i2c_bus_read / i2c_bus_write with the same
 * signature. These thin wrappers delegate to the PAL so every driver compiles
 * unchanged on every target.
 */

int i2c_bus_read(uint8_t bus, uint8_t addr, uint8_t reg,
                 uint8_t *buf, uint16_t len) {
    return pal_i2c_read(bus, addr, reg, buf, len);
}

int i2c_bus_write(uint8_t bus, uint8_t addr, uint8_t reg,
                  const uint8_t *buf, uint16_t len) {
    return pal_i2c_write(bus, addr, reg, buf, len);
}

/* ── SPI ─────────────────────────────────────────────────────────────────── */

static SPI_HandleTypeDef *s_spi_handle[PAL_SPI_MAX_BUSES] = {NULL, NULL};

pal_err_t pal_spi_init(uint8_t bus, int sck, int mosi, int miso,
                        uint32_t speed_hz, uint8_t mode) {
    (void)sck; (void)mosi; (void)miso; (void)speed_hz; (void)mode;
    /* Pins and clock divider configured by CubeMX; store handle reference. */
    if (bus >= PAL_SPI_MAX_BUSES) return PAL_ERR_INVALID;
    s_spi_handle[bus] = (bus == 0) ? &hspi1 : &hspi2;
    return PAL_OK;
}

pal_err_t pal_spi_deinit(uint8_t bus) {
    if (bus >= PAL_SPI_MAX_BUSES || !s_spi_handle[bus]) return PAL_ERR_INVALID;
    HAL_SPI_DeInit(s_spi_handle[bus]);
    s_spi_handle[bus] = NULL;
    return PAL_OK;
}

pal_err_t pal_spi_transfer(uint8_t bus, int cs_pin,
                             const uint8_t *tx, uint8_t *rx, size_t len) {
    if (bus >= PAL_SPI_MAX_BUSES || !s_spi_handle[bus]) return PAL_ERR_INVALID;
    HAL_GPIO_WritePin(pin_to_port(cs_pin), pin_to_mask(cs_pin), GPIO_PIN_RESET);
    HAL_StatusTypeDef st = HAL_SPI_TransmitReceive(
        s_spi_handle[bus], (uint8_t *)tx, rx, (uint16_t)len, 100U);
    HAL_GPIO_WritePin(pin_to_port(cs_pin), pin_to_mask(cs_pin), GPIO_PIN_SET);
    return (st == HAL_OK) ? PAL_OK : PAL_ERR_FAIL;
}

pal_err_t pal_spi_write(uint8_t bus, int cs_pin,
                          const uint8_t *tx, size_t len) {
    if (bus >= PAL_SPI_MAX_BUSES || !s_spi_handle[bus]) return PAL_ERR_INVALID;
    HAL_GPIO_WritePin(pin_to_port(cs_pin), pin_to_mask(cs_pin), GPIO_PIN_RESET);
    HAL_StatusTypeDef st = HAL_SPI_Transmit(
        s_spi_handle[bus], (uint8_t *)tx, (uint16_t)len, 100U);
    HAL_GPIO_WritePin(pin_to_port(cs_pin), pin_to_mask(cs_pin), GPIO_PIN_SET);
    return (st == HAL_OK) ? PAL_OK : PAL_ERR_FAIL;
}

/* ── PWM ─────────────────────────────────────────────────────────────────── */

/*
 * Channel mapping:
 *   PAL channels 0-3 → TIM3 channels 1-4
 *   PAL channels 4-7 → TIM4 channels 1-4
 */

typedef struct {
    bool     active;
    uint8_t  res_bits;
    uint32_t freq_hz;
} pwm_state_t;

static pwm_state_t s_pwm[PAL_PWM_MAX_CHANNELS];

static TIM_HandleTypeDef *pwm_get_tim(uint8_t ch) {
    return (ch < 4) ? &htim3 : &htim4;
}

static uint32_t pwm_get_tim_ch(uint8_t ch) {
    static const uint32_t map[4] = {
        TIM_CHANNEL_1, TIM_CHANNEL_2, TIM_CHANNEL_3, TIM_CHANNEL_4
    };
    return map[ch & 0x03];
}

pal_err_t pal_pwm_init(uint8_t channel, int pin, uint32_t freq_hz,
                        uint8_t resolution_bits) {
    (void)pin;  /* Pin AF configured by CubeMX. */
    if (channel >= PAL_PWM_MAX_CHANNELS) return PAL_ERR_INVALID;

    TIM_HandleTypeDef *htim = pwm_get_tim(channel);
    uint32_t tim_ch         = pwm_get_tim_ch(channel);

    /* Update ARR to match requested frequency.
     * ARR = (SystemCoreClock / (PSC+1) / freq_hz) - 1
     * Use prescaler such that ARR fits in 16 bits and matches resolution. */
    uint32_t arr = (1UL << resolution_bits) - 1UL;
    uint32_t psc = (SystemCoreClock / ((arr + 1UL) * freq_hz));
    if (psc > 0) psc--;

    htim->Init.Prescaler = psc;
    htim->Init.Period    = arr;
    HAL_TIM_PWM_Init(htim);

    TIM_OC_InitTypeDef oc = {0};
    oc.OCMode     = TIM_OCMODE_PWM1;
    oc.Pulse      = 0;
    oc.OCPolarity = TIM_OCPOLARITY_HIGH;
    oc.OCFastMode = TIM_OCFAST_DISABLE;
    HAL_TIM_PWM_ConfigChannel(htim, &oc, tim_ch);

    HAL_TIM_PWM_Start(htim, tim_ch);

    s_pwm[channel].active   = true;
    s_pwm[channel].res_bits = resolution_bits;
    s_pwm[channel].freq_hz  = freq_hz;
    return PAL_OK;
}

pal_err_t pal_pwm_deinit(uint8_t channel) {
    if (channel >= PAL_PWM_MAX_CHANNELS || !s_pwm[channel].active)
        return PAL_ERR_INVALID;
    HAL_TIM_PWM_Stop(pwm_get_tim(channel), pwm_get_tim_ch(channel));
    s_pwm[channel].active = false;
    return PAL_OK;
}

pal_err_t pal_pwm_set_duty(uint8_t channel, uint32_t duty) {
    if (channel >= PAL_PWM_MAX_CHANNELS || !s_pwm[channel].active)
        return PAL_ERR_INVALID;
    __HAL_TIM_SET_COMPARE(pwm_get_tim(channel), pwm_get_tim_ch(channel), duty);
    return PAL_OK;
}

pal_err_t pal_pwm_set_freq(uint8_t channel, uint32_t freq_hz) {
    if (channel >= PAL_PWM_MAX_CHANNELS || !s_pwm[channel].active)
        return PAL_ERR_INVALID;

    TIM_HandleTypeDef *htim = pwm_get_tim(channel);
    uint32_t arr = (1UL << s_pwm[channel].res_bits) - 1UL;
    uint32_t psc = (SystemCoreClock / ((arr + 1UL) * freq_hz));
    if (psc > 0) psc--;

    htim->Instance->PSC = psc;
    htim->Instance->ARR = arr;
    htim->Instance->EGR = TIM_EGR_UG;  /* Apply immediately. */

    s_pwm[channel].freq_hz = freq_hz;
    return PAL_OK;
}

uint32_t pal_pwm_get_max_duty(uint8_t resolution_bits) {
    return (1UL << resolution_bits) - 1UL;
}

/* ── ADC ─────────────────────────────────────────────────────────────────── */

/*
 * Maps a PAL pin number to an ADC channel number.
 * STM32F4 ADC1 channel map (IN0-IN15 on PA0-PA7, PB0-PB1, PC0-PC5).
 */
static uint32_t pin_to_adc_channel(int pin) {
    /* PA0-PA7 → ADC_CHANNEL_0-7 */
    if (pin >= 0 && pin <= 7)   return (uint32_t)(ADC_CHANNEL_0 + pin);
    /* PB0 → ADC_CHANNEL_8, PB1 → ADC_CHANNEL_9 */
    if (pin == 16) return ADC_CHANNEL_8;
    if (pin == 17) return ADC_CHANNEL_9;
    /* PC0-PC5 → ADC_CHANNEL_10-15 */
    if (pin >= 32 && pin <= 37) return (uint32_t)(ADC_CHANNEL_10 + (pin - 32));
    return ADC_CHANNEL_0;
}

static uint32_t s_adc_channel[8] = {ADC_CHANNEL_0};
static bool     s_adc_init[8]    = {false};

pal_err_t pal_adc_init(uint8_t channel, int pin) {
    if (channel >= 8) return PAL_ERR_INVALID;

    s_adc_channel[channel] = pin_to_adc_channel(pin);

    ADC_ChannelConfTypeDef cfg = {0};
    cfg.Channel      = s_adc_channel[channel];
    cfg.Rank         = 1;
    cfg.SamplingTime = ADC_SAMPLETIME_84CYCLES;
    cfg.Offset       = 0;

    if (HAL_ADC_ConfigChannel(&hadc1, &cfg) != HAL_OK) return PAL_ERR_FAIL;
    s_adc_init[channel] = true;
    return PAL_OK;
}

uint16_t pal_adc_read(uint8_t channel) {
    if (channel >= 8 || !s_adc_init[channel]) return 0;

    /* Re-select the channel before each conversion. */
    ADC_ChannelConfTypeDef cfg = {0};
    cfg.Channel      = s_adc_channel[channel];
    cfg.Rank         = 1;
    cfg.SamplingTime = ADC_SAMPLETIME_84CYCLES;
    cfg.Offset       = 0;
    HAL_ADC_ConfigChannel(&hadc1, &cfg);

    HAL_ADC_Start(&hadc1);
    if (HAL_ADC_PollForConversion(&hadc1, 10U) != HAL_OK) {
        HAL_ADC_Stop(&hadc1);
        return 0;
    }
    uint32_t val = HAL_ADC_GetValue(&hadc1);
    HAL_ADC_Stop(&hadc1);

    /* Clamp to 12-bit range (hadc1 configured for 12-bit resolution). */
    if (val > 4095U) val = 4095U;
    return (uint16_t)val;
}

float pal_adc_read_voltage(uint8_t channel) {
    return (pal_adc_read(channel) / 4095.0f) * 3.3f;
}

/* ── UART ────────────────────────────────────────────────────────────────── */

static UART_HandleTypeDef *s_uart_handle[PAL_UART_MAX_PORTS] = {NULL, NULL, NULL};

pal_err_t pal_uart_init(uint8_t port, int tx_pin, int rx_pin, uint32_t baud) {
    (void)tx_pin; (void)rx_pin;  /* Pins configured by CubeMX. */
    if (port >= PAL_UART_MAX_PORTS) return PAL_ERR_INVALID;

    UART_HandleTypeDef *h;
    switch (port) {
        case 0:  h = &huart1; break;
        case 1:  h = &huart2; break;
        default: h = &huart3; break;
    }
    s_uart_handle[port] = h;

    if (h->Init.BaudRate != baud) {
        HAL_UART_DeInit(h);
        h->Init.BaudRate     = baud;
        h->Init.WordLength   = UART_WORDLENGTH_8B;
        h->Init.StopBits     = UART_STOPBITS_1;
        h->Init.Parity       = UART_PARITY_NONE;
        h->Init.Mode         = UART_MODE_TX_RX;
        h->Init.HwFlowCtl    = UART_HWCONTROL_NONE;
        h->Init.OverSampling = UART_OVERSAMPLING_16;
        if (HAL_UART_Init(h) != HAL_OK) return PAL_ERR_FAIL;
    }
    return PAL_OK;
}

pal_err_t pal_uart_deinit(uint8_t port) {
    if (port >= PAL_UART_MAX_PORTS || !s_uart_handle[port]) return PAL_ERR_INVALID;
    HAL_UART_DeInit(s_uart_handle[port]);
    s_uart_handle[port] = NULL;
    return PAL_OK;
}

/*
 * pal_uart_available: STM32Cube HAL does not expose a simple buffered-byte
 * count without DMA or interrupt-driven ring-buffers. Returns 0; applications
 * that need non-blocking checks should use HAL_UART_Receive_IT with a custom
 * ring buffer instead.
 */
int pal_uart_available(uint8_t port) {
    (void)port;
    return 0;
}

int pal_uart_read_byte(uint8_t port, uint32_t timeout_ms) {
    if (port >= PAL_UART_MAX_PORTS || !s_uart_handle[port]) return -1;
    uint8_t b;
    HAL_StatusTypeDef st = HAL_UART_Receive(s_uart_handle[port], &b, 1U, timeout_ms);
    return (st == HAL_OK) ? (int)b : -1;
}

int pal_uart_read(uint8_t port, uint8_t *buf, size_t len, uint32_t timeout_ms) {
    if (port >= PAL_UART_MAX_PORTS || !s_uart_handle[port]) return -1;
    HAL_StatusTypeDef st = HAL_UART_Receive(
        s_uart_handle[port], buf, (uint16_t)len, timeout_ms);
    if (st == HAL_OK) return (int)len;
    if (st == HAL_TIMEOUT) return 0;
    return -1;
}

pal_err_t pal_uart_write(uint8_t port, const uint8_t *buf, size_t len) {
    if (port >= PAL_UART_MAX_PORTS || !s_uart_handle[port]) return PAL_ERR_INVALID;
    HAL_StatusTypeDef st = HAL_UART_Transmit(
        s_uart_handle[port], (uint8_t *)buf, (uint16_t)len, 100U);
    return (st == HAL_OK) ? PAL_OK : PAL_ERR_FAIL;
}

/* ── I2S ─────────────────────────────────────────────────────────────────── */

pal_err_t pal_i2s_init(uint8_t port, pal_i2s_dir_t dir,
                        int bclk, int ws, int data,
                        uint32_t sample_rate, uint8_t bits) {
    (void)port; (void)bclk; (void)ws; (void)data;
    /* Only port 0 is supported via hi2s2; configured by CubeMX. */
    HAL_I2S_DeInit(&hi2s2);
    hi2s2.Init.Mode          = (dir == PAL_I2S_DIR_TX) ? I2S_MODE_MASTER_TX
                                                        : I2S_MODE_MASTER_RX;
    hi2s2.Init.Standard      = I2S_STANDARD_PHILIPS;
    hi2s2.Init.DataFormat    = (bits == 32) ? I2S_DATAFORMAT_32B : I2S_DATAFORMAT_16B;
    hi2s2.Init.MCLKOutput    = I2S_MCLKOUTPUT_DISABLE;
    hi2s2.Init.AudioFreq     = sample_rate;
    hi2s2.Init.CPOL          = I2S_CPOL_LOW;
    hi2s2.Init.ClockSource   = I2S_CLOCK_PLL;
    hi2s2.Init.FullDuplexMode = I2S_FULLDUPLEXMODE_DISABLE;
    return (HAL_I2S_Init(&hi2s2) == HAL_OK) ? PAL_OK : PAL_ERR_FAIL;
}

pal_err_t pal_i2s_deinit(uint8_t port) {
    (void)port;
    HAL_I2S_DeInit(&hi2s2);
    return PAL_OK;
}

pal_err_t pal_i2s_read(uint8_t port, void *buf, size_t len, size_t *bytes_read) {
    (void)port;
    /* HAL_I2S_Receive expects length in number of 16-bit half-words. */
    uint16_t hw_count = (uint16_t)(len / 2U);
    HAL_StatusTypeDef st = HAL_I2S_Receive(&hi2s2, (uint16_t *)buf, hw_count, 100U);
    if (bytes_read) *bytes_read = (st == HAL_OK) ? len : 0U;
    return (st == HAL_OK) ? PAL_OK : PAL_ERR_FAIL;
}

pal_err_t pal_i2s_write(uint8_t port, const void *buf, size_t len,
                          size_t *bytes_written) {
    (void)port;
    uint16_t hw_count = (uint16_t)(len / 2U);
    HAL_StatusTypeDef st = HAL_I2S_Transmit(&hi2s2, (uint16_t *)buf, hw_count, 100U);
    if (bytes_written) *bytes_written = (st == HAL_OK) ? len : 0U;
    return (st == HAL_OK) ? PAL_OK : PAL_ERR_FAIL;
}

/* ── NVS — Flash emulation ───────────────────────────────────────────────── */

/*
 * Storage layout (2 KB region starting at NVS_FLASH_ADDR, sector 11 on
 * STM32F407 @ 0x080E0000):
 *
 *   [key_len : 1 byte][key : key_len bytes][val_len : 2 bytes LE][val : val_len bytes]
 *   ... repeated ...
 *   [0xFF ... end of sector] — erased/empty area
 *
 * Entries are scanned linearly. A key_len of 0xFF indicates unused space.
 */

#define NVS_FLASH_ADDR  0x080E0000UL
#define NVS_REGION_SIZE 2048U
#define NVS_SECTOR_NUM  11U          /* FLASH_SECTOR_11 on STM32F407 */

static const uint8_t *nvs_base(void) {
    return (const uint8_t *)NVS_FLASH_ADDR;
}

/*
 * Find entry for key. Returns pointer to the first byte of the entry
 * (key_len field), or NULL if not found. val_out and val_len_out are set
 * when found.
 */
static const uint8_t *nvs_find(const char *key,
                                const uint8_t **val_out,
                                uint16_t      *val_len_out) {
    const uint8_t *p   = nvs_base();
    const uint8_t *end = p + NVS_REGION_SIZE;
    size_t         klen = strlen(key);

    while (p < end) {
        uint8_t entry_klen = p[0];
        if (entry_klen == 0xFF) break;         /* End of written entries. */
        if (entry_klen == 0)    { p++; continue; }

        const uint8_t *kstart  = p + 1;
        if (kstart + entry_klen + 2 > end) break;

        uint16_t vlen = (uint16_t)kstart[entry_klen] |
                        (uint16_t)(kstart[entry_klen + 1] << 8);
        const uint8_t *vstart = kstart + entry_klen + 2;

        if (vstart + vlen > end) break;

        if (entry_klen == (uint8_t)klen &&
                memcmp(kstart, key, klen) == 0) {
            if (val_out)     *val_out     = vstart;
            if (val_len_out) *val_len_out = vlen;
            return p;
        }
        p = vstart + vlen;
    }
    return NULL;
}

/* Find the first free byte position (after all written entries). */
static const uint8_t *nvs_free_ptr(void) {
    const uint8_t *p   = nvs_base();
    const uint8_t *end = p + NVS_REGION_SIZE;

    while (p < end) {
        uint8_t entry_klen = p[0];
        if (entry_klen == 0xFF) return p;
        if (entry_klen == 0)  { p++; continue; }

        const uint8_t *kstart = p + 1;
        if (kstart + entry_klen + 2 > end) return end;

        uint16_t vlen = (uint16_t)kstart[entry_klen] |
                        (uint16_t)(kstart[entry_klen + 1] << 8);
        p = kstart + entry_klen + 2 + vlen;
    }
    return end;
}

static pal_err_t nvs_erase_sector(void) {
    FLASH_EraseInitTypeDef er = {0};
    er.TypeErase    = FLASH_TYPEERASE_SECTORS;
    er.VoltageRange = FLASH_VOLTAGE_RANGE_3;
    er.Sector       = NVS_SECTOR_NUM;
    er.NbSectors    = 1;
    uint32_t sector_err = 0;

    HAL_FLASH_Unlock();
    HAL_StatusTypeDef st = HAL_FLASHEx_Erase(&er, &sector_err);
    HAL_FLASH_Lock();
    return (st == HAL_OK) ? PAL_OK : PAL_ERR_FAIL;
}

static pal_err_t nvs_write_bytes(uint32_t addr, const uint8_t *data, size_t len) {
    HAL_FLASH_Unlock();
    for (size_t i = 0; i < len; i++) {
        if (HAL_FLASH_Program(FLASH_TYPEPROGRAM_BYTE,
                              addr + i, (uint64_t)data[i]) != HAL_OK) {
            HAL_FLASH_Lock();
            return PAL_ERR_FAIL;
        }
    }
    HAL_FLASH_Lock();
    return PAL_OK;
}

pal_err_t pal_nvs_get(const char *key, void *data, size_t *len) {
    const uint8_t *val;
    uint16_t       val_len;

    if (!nvs_find(key, &val, &val_len)) return PAL_ERR_NOT_FOUND;

    size_t copy_len = (*len < val_len) ? *len : val_len;
    memcpy(data, val, copy_len);
    *len = val_len;
    return PAL_OK;
}

pal_err_t pal_nvs_set(const char *key, const void *data, size_t len) {
    size_t klen = strlen(key);
    if (klen > 255U || len > 65535U) return PAL_ERR_INVALID;

    /* Entry size: 1 (klen) + klen + 2 (vlen) + len */
    size_t entry_size = 1U + klen + 2U + len;

    const uint8_t *free_ptr = nvs_free_ptr();
    size_t         used     = (size_t)(free_ptr - nvs_base());

    if (used + entry_size > NVS_REGION_SIZE) return PAL_ERR_NO_MEM;

    uint32_t write_addr = NVS_FLASH_ADDR + (uint32_t)used;

    uint8_t  klen_byte  = (uint8_t)klen;
    uint8_t  vlen_lo    = (uint8_t)(len & 0xFFU);
    uint8_t  vlen_hi    = (uint8_t)((len >> 8) & 0xFFU);

    HAL_FLASH_Unlock();

    /* Write key_len */
    if (HAL_FLASH_Program(FLASH_TYPEPROGRAM_BYTE, write_addr,
                          (uint64_t)klen_byte) != HAL_OK) {
        HAL_FLASH_Lock();
        return PAL_ERR_FAIL;
    }
    write_addr++;

    /* Write key bytes */
    for (size_t i = 0; i < klen; i++) {
        if (HAL_FLASH_Program(FLASH_TYPEPROGRAM_BYTE, write_addr,
                              (uint64_t)((const uint8_t *)key)[i]) != HAL_OK) {
            HAL_FLASH_Lock();
            return PAL_ERR_FAIL;
        }
        write_addr++;
    }

    /* Write val_len (2 bytes LE) */
    if (HAL_FLASH_Program(FLASH_TYPEPROGRAM_BYTE, write_addr,
                          (uint64_t)vlen_lo) != HAL_OK ||
        HAL_FLASH_Program(FLASH_TYPEPROGRAM_BYTE, write_addr + 1U,
                          (uint64_t)vlen_hi) != HAL_OK) {
        HAL_FLASH_Lock();
        return PAL_ERR_FAIL;
    }
    write_addr += 2U;

    HAL_FLASH_Lock();

    /* Write value payload */
    return nvs_write_bytes(write_addr, (const uint8_t *)data, len);
}

pal_err_t pal_nvs_erase(const char *key) {
    /*
     * Flash can only be erased at sector granularity on STM32F4. Erasing a
     * single key therefore erases the entire NVS region. Callers should treat
     * pal_nvs_erase as a bulk-erase operation and re-write any entries they
     * want to keep afterwards.
     */
    (void)key;
    return nvs_erase_sector();
}

/* ── One-Wire (bit-bang — shared implementation) ─────────────────────────── */
/*
 * The One-Wire protocol is implemented entirely through pal_gpio_set_direction,
 * pal_gpio_set_level, pal_gpio_get_level, and pal_delay_us, all of which are
 * provided above. The shared pal_onewire.c in hal/ therefore compiles and
 * links correctly against this translation unit without any additional code.
 */
