"""Local inference engine for CodeLM."""

from dataclasses import dataclass
from pathlib import Path

import torch
import torch.nn.functional as F

from config import TOP_K, TOP_P, TEMPERATURE, MAX_GENERATE_LEN, MODEL_DIR
from model.architecture import CodeLM
from model.tokenizer import BlockTokenizer


@dataclass
class FirmwareResult:
    """Result of firmware generation."""
    block_sequence: list[str]
    source_code: str
    target_mcu: str
    confidence: float
    constraint_scores: dict[str, float]


def load_model(checkpoint: Path | None = None) -> tuple[CodeLM, BlockTokenizer]:
    """Load a trained CodeLM model and tokenizer."""
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    model = CodeLM()

    if checkpoint and checkpoint.exists():
        model.load_state_dict(torch.load(checkpoint, map_location=device, weights_only=True))
    else:
        # Look for latest checkpoint
        ckpts = sorted(MODEL_DIR.glob("codelm_epoch_*.pt"))
        if ckpts:
            model.load_state_dict(torch.load(ckpts[-1], map_location=device, weights_only=True))

    model = model.to(device).eval()

    tokenizer_path = MODEL_DIR / "tokenizer.json"
    if tokenizer_path.exists():
        tokenizer = BlockTokenizer.load(tokenizer_path)
    else:
        tokenizer = BlockTokenizer()

    return model, tokenizer


def top_k_top_p_filtering(
    logits: torch.Tensor,
    top_k: int = TOP_K,
    top_p: float = TOP_P,
) -> torch.Tensor:
    """Apply top-k and nucleus (top-p) filtering to logits."""
    if top_k > 0:
        values, _ = torch.topk(logits, top_k)
        min_val = values[:, -1].unsqueeze(-1)
        logits = torch.where(logits < min_val, torch.full_like(logits, float("-inf")), logits)

    if top_p < 1.0:
        sorted_logits, sorted_indices = torch.sort(logits, descending=True)
        cumulative_probs = torch.cumsum(F.softmax(sorted_logits, dim=-1), dim=-1)
        sorted_mask = cumulative_probs - F.softmax(sorted_logits, dim=-1) > top_p
        sorted_logits[sorted_mask] = float("-inf")
        logits = sorted_logits.scatter(1, sorted_indices, sorted_logits)

    return logits


@torch.no_grad()
def generate_block_sequence(
    model: CodeLM,
    tokenizer: BlockTokenizer,
    intent_tokens: list[int],
    max_len: int = MAX_GENERATE_LEN,
    temperature: float = TEMPERATURE,
) -> list[int]:
    """Autoregressively generate a block sequence."""
    device = next(model.parameters()).device
    input_ids = torch.tensor([intent_tokens], dtype=torch.long, device=device)

    for _ in range(max_len):
        logits = model(input_ids)
        next_logits = logits[:, -1, :] / temperature
        next_logits = top_k_top_p_filtering(next_logits)
        probs = F.softmax(next_logits, dim=-1)
        next_token = torch.multinomial(probs, num_samples=1)

        if next_token.item() == 2:  # <EOS>
            break

        input_ids = torch.cat([input_ids, next_token], dim=1)

    return input_ids[0].tolist()


def generate_firmware(
    intent: str,
    target_mcu: str = "esp32s3",
    checkpoint: Path | None = None,
) -> FirmwareResult:
    """Generate firmware from a natural-language intent.

    Pipeline:
      1. Encode intent into embedding
      2. Retrieve candidate blocks via FAISS similarity search
      3. Seed the model with retrieved block tokens
      4. Autoregressive generation of remaining block sequence
      5. Compose blocks into full firmware source
    """
    model, tokenizer = load_model(checkpoint)

    # For now, use a simple approach: start with BOS and generate
    seed_tokens = [1]  # <BOS>
    generated = generate_block_sequence(model, tokenizer, seed_tokens)
    block_ids = tokenizer.decode(generated)

    # Compose blocks into source code
    source_code = _compose_source(block_ids, target_mcu)

    return FirmwareResult(
        block_sequence=block_ids,
        source_code=source_code,
        target_mcu=target_mcu,
        confidence=0.0,
        constraint_scores={
            "stack_ok": 0.0,
            "no_conflicts": 0.0,
            "timing_ok": 0.0,
            "deps_ok": 0.0,
        },
    )


def _compose_source(block_ids: list[str], target_mcu: str) -> str:
    """Compose block IDs into a complete firmware source file."""
    from corpus.db.schema import get_session, Block

    session = get_session()
    blocks = []
    for bid in block_ids:
        if bid in ("<UNK>", "<SEP>"):
            continue
        block = session.query(Block).filter(Block.block_id == bid).first()
        if block:
            blocks.append(block.body)

    if not blocks:
        return f"// CodeLM: No blocks found for target {target_mcu}\n// Retrain the model with corpus data.\n"

    header = f"// Generated by CodeLM for {target_mcu}\n// Block count: {len(blocks)}\n\n"
    return header + "\n\n".join(blocks)
