apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: parakram

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - ingress.yaml
  - podmonitor.yaml
  # secret.yaml is NOT listed — create it manually per environment

commonLabels:
  app.kubernetes.io/name: parakram
  app.kubernetes.io/part-of: parakram-platform
