apiVersion: v1
kind: Service
metadata:
  name: parakram-backend
  namespace: parakram
  labels:
    app: parakram
    component: backend
spec:
  type: ClusterIP
  selector:
    app: parakram
    component: backend
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
